### ISSUE TITLE
Plugin Development : Osmosis

### ISSUE THREAD

**Issue by meetrick** [dsrvlabs/vatz#121]
- Parents: https://github.com/dsrvlabs/vatz/issues/88

---
 
## Checklist

- [x] New Feature for the Service/Plugin (Vatz)
- [ ] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
- We need plugin for monitoring Osmosis node.

### **Describe the solution you'd like| Ex**
- Check node Uptime (health check)
- Check block sync
- Check cpu, memory usage
- connected peer count

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

### **Additional context or comment**
> Add any other context or screenshots about the feature request here.

**Comment by xellos00** [comment]
As discussed with @meetrick 
osmosis plugin can implemented with 
- vatz-plugin-sysutil
- vatz-plugin-cosmoshub

and therefore I close this issue.
