### ISSUE TITLE
Plugin Development : Relayer 

### ISSUE THREAD

**Issue by meetrick** [dsrvlabs/vatz#152]
## Checklist

- [x] New Feature for the Service/Plugin (Vatz)
- [ ] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
- My feature is monitoring tools for relayer node

### **Describe the solution you'd like| Ex**
- checked process is alived
- checked relayer accounts balances
- checked un-relayed packet

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

**Comment by gnongs** [comment]
## 2022-12-15
You have created an earlier version, and the code is in [this repo](https://github.com/dsrvlabs/vatz-plugin-relayer).
