### ISSUE TITLE
Plugin Development : Persistence

### ISSUE THREAD

**Issue by kim201212** [dsrvlabs/vatz#156]
- Parents: https://github.com/dsrvlabs/vatz/issues/88

---

## Checklist

- [x] New Feature for the Service/Plugin (Vatz)
- [ ] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. such as Ex. I'm always frustrated

Initial plugin development.

### **Describe the solution you'd like| Ex**
> A clear and concise description of what you want to happen

New plugin project will do
- Check process up
- Check block height for persistenceCore

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

N/A

### **Additional context or comment**
> Add any other context or screenshots about the feature request here.

**Comment by xellos00** [comment]
@kim201212 
Are you still working on this? 
I think you've finished this issue with single plugin. 
Let me know if you still need to open this issue.
