### ISSUE TITLE
Plugin Development: Common part

### ISSUE THREAD

**Issue by rootwarp** [dsrvlabs/vatz#162]
- Parents: https://github.com/dsrvlabs/vatz/issues/88

---

## Checklist

- [X] New Feature for the Service/Plugin (Vatz)
- [ ] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. such as Ex. I'm always frustrated

### **Describe the solution you'd like| Ex**
> A clear and concise description of what you want to happen

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

### **Additional context or comment**
> Add any other context or screenshots about the feature request here.

---
- OS
  - [x] #168
  - [ ] Memory
  - [ ] CPU
- Cosmos Family
  - [x] https://github.com/dsrvlabs/vatz-plugin-common/issues/1
  - [ ] Process up
  - [ ] Block signing

- Eth derived
  - [ ] Block height
  - [ ] Process up
  - [ ] Block signing

**Comment by xellos00** [comment]
@rootwarp 
Can I close this issue because I think official plugin handle these items you mentioned above.

**Comment by rootwarp** [comment]
> @rootwarp 
> 
> Can I close this issue because I think official plugin handle these items you mentioned above. 

@xellos00 Agree.
