### ISSUE TITLE
Prometheus integration

### ISSUE THREAD

**Issue by heejin-github** [dsrvlabs/vatz#169]
## Checklist

- [x] New Feature for the Service/Plugin (Vatz)
- [ ] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. such as Ex. I'm always frustrated

There's no method to monitor vatz itself. we need monitoring system for vatz.
Let's start to integrate prometheus from this issue, and we'll handle monitoring for vatz liveness in this issue first.

### **Describe the solution you'd like| Ex**
> A clear and concise description of what you want to happen

serve prometheus metrics of `liveness` for vatz monitoring.

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

 #166 vatz health checker will monitor vatz together.

### **Additional context or comment**
> Add any other context or screenshots about the feature request here.

**Comment by xellos00** [comment]
Prometheus integration is finished.
