### ISSUE TITLE
Plugin Development: Avoid recurring alerts of the same type

### ISSUE THREAD

**Issue by gnongs** [dsrvlabs/vatz#177]
- Related: #163 

--- 
## Checklist

- [ ] New Feature for the Service/Plugin (Vatz)
- [x] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. such as Ex. I'm always frustrated

Alert with the same content occur repeatedly.
<img width="145" alt="image" src="https://user-images.githubusercontent.com/65050483/178180626-0f60a254-23db-464a-bf9b-29bd748d0ec4.png">

### **Describe the solution you'd like| Ex**
> A clear and concise description of what you want to happen

Fix to prevent alerts for the same issue from continuing to occur.

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

Manage messages as one variable for sending messages

### **Additional context or comment**
> Add any other context or screenshots about the feature request here.

**Comment by xellos00** [comment]
@gnongs 
We can close this issue, right?

**Comment by gnongs** [comment]
@xellos00 Yes! I will close this issue.
