### ISSUE TITLE
Developments for VATZ CLI Commands 

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#178]
- Related: #107 

---

## Checklist

- [x] #208
- [ ] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. such as Ex. I'm always frustrated

### **Describe the solution you'd like| Ex**
> A clear and concise description of what you want to happen

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

---

# Child Issue(List up)

- [x] https://github.com/dsrvlabs/vatz/issues/208
- [x] #386
- [ ] `vatz help`
- [x] #213 
   - [ ] Remove default.yaml due to PR order.  
- [x] #220
- [x] #277
- [x] #278

**Comment by rootwarp** [comment]
@xellos00 `vatz help` command does not necessary because `cobra` package already provides similar one.
what do you thing?

**Comment by xellos00** [comment]
> @xellos00 `vatz help` command does not necessary because `cobra` package already provides similar one. what do you thing?

I agree!!. Would you close this issue if you don't mind?
