### ISSUE TITLE
Plugin Development : Sei

### ISSUE THREAD

**Issue by meetrick** [dsrvlabs/vatz#184]
## Checklist

- [x] New Feature for the Service/Plugin (Vatz)
- [ ] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
- My feature is monitoring tools for relayer node

### **Describe the solution you'd like| Ex**
- checked process is alived
- checked Block Height

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

### **Additional context or comment**
> Add any other context or screenshots about the feature request here.

**Comment by xellos00** [comment]
@meetrick 
We can close this issue, right?

**Comment by xellos00** [comment]
Close this issue, if there's any issue regarding Sei-plugin, will be handled on vatz-plugin-sei
