### ISSUE TITLE
Signing for Every Commit

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#195]
### Checklist
- [ ] Bug from Service (Vatz)
- [ ] Bug from Plugin (Vatz) 
- [ ] Malfunction on CI/CD 
- [x] etc(e.g, Hardware version doesn't match, )

---

@dsrvlabs/validator 
Please, Check you've signed when you commit all your work
Refer to https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work 

Merging is blocked If you don't signed for your work reference on github unless you do this on command line.
This issue were occurred many times previous merges and I personally handled this before, but 
Internally we've got to fixed for all Validators team. 

![image](https://user-images.githubusercontent.com/6308023/180312659-ee33163c-0a9b-4604-b3fe-dbf0bcce2a25.png)

**Comment by xellos00** [comment]
s

> 

@qkrybin 
<img width="907" alt="image" src="https://user-images.githubusercontent.com/6308023/211105170-81c62e05-7256-4855-8eba-8cd5df3820c7.png">
Reference link:
- https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification
 
We have this issue previously, and I missed to asked you for this process, 
- https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
Can you follow the instruction above?

**Comment by xellos00** [comment]
> @dsrvlabs/validator Please, check out if you set `commit.gpgsign` true on your git config.
> 
> * [ ]  @hqueue
> * [x]  @heejin-github
> * [x]  @rootwarp
> * [x]  @Choi-Jinhong
> * [x]  @kim201212
> * [x]  @skonhwang
> * [x]  @meetrick
> * [x]  @xellos00
> * [ ]  @qkrybin


@qkrybin 
<img width="907" alt="image" src="https://user-images.githubusercontent.com/6308023/211105170-81c62e05-7256-4855-8eba-8cd5df3820c7.png">
Reference link:
- https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification
 
We have this issue previously, and I missed to asked you for this process, 
- https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work
Can you follow the instruction above?

**Comment by qkrybin** [comment]
> @qkrybin, @hqueue 지금 다시금 이슈를 정리하고 있습니다. 그렇게 얼마 걸리지 않는 일이니, 작업 해주시면 감사하겠습니다. Comment 주시면 감사하겠습니다.

이렇게 하면 되는 걸까요 @xellos00 
```
youngbin@LT-016-youngbin ~ % git config --global commit.gpgsign true 
youngbin@LT-016-youngbin ~ % git config commit.gpgsign
true
```

**Comment by xellos00** [comment]
> > @qkrybin, @hqueue 지금 다시금 이슈를 정리하고 있습니다. 그렇게 얼마 걸리지 않는 일이니, 작업 해주시면 감사하겠습니다. Comment 주시면 감사하겠습니다.
> 
> 이렇게 하면 되는 걸까요 @xellos00
> 
> ```
> youngbin@LT-016-youngbin ~ % git config --global commit.gpgsign true 
> youngbin@LT-016-youngbin ~ % git config commit.gpgsign
> true
> ```

네 감사합니다.

**Comment by hqueue** [comment]
```
hqueue@Albireo2022:~ $ git config commit.gpgsign
true
```

@xellos00 Thanks for the heads up :)
