### ISSUE TITLE
Check Test & Coverage automatically

### ISSUE THREAD

**Issue by kim201212** [dsrvlabs/vatz#197]
- Parents: #248 
---
### **What does it require to on Vatz**
> A clear and concise description of what you expected to happen through Ci/CD

Vatz needs to check golang test & coverage automatically.

### **Expected behavior**
> A clear and concise description of results after CI/CD implementation.

Coder can know the test result in the comments.

### **How to run**
> Please, Update and give simple guide to run CI/CD process with this issue. 

### **Screenshots**
> If applicable, add screenshots to help explain your problem

**Comment by xellos00** [comment]
@kim201212 
Everything is public now, is this Go lint auto check on Github action?
