### ISSUE TITLE
Manage default config content at one place.

### ISSUE THREAD

**Issue by rootwarp** [dsrvlabs/vatz#258]
## Checklist
- [ ] New Feature for the SVC/Plugin
- [ ] New Feature for CI/CD
- [X] Enhancement on Vatz
- [ ] Others(etc. e.g, documentation,...)
---

### **Please describe, what it's about or related Problem with**
> A clear description of what feature need to be developed or enhanced in Vatz 

The VATZ initialize command creates config file by default configuration setting.
The default config template is hardcoded at `cmd.go` file but the test fixture for config module is stored separately.

Due to the default contents of testing and initializing are separated on code,
it is hard to manage and the developer should be check carefully.

### **Describe the output that you are expecting for above**
> A clear and concise description of what you expect to happen.

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

### **Additional context**
> Add any other context or screenshots about the feature request here.

**Comment by xellos00** [comment]
@rootwarp 
We had added `home_path` in default yaml, so we can close this issue. 
I am going to close this issue unless you do have other concern with this. 
Please, let me know if there's anything.

**Comment by rootwarp** [comment]
@xellos00 Make sense. I'll fix this.
