### ISSUE TITLE
Cosmos - Plugin - CI for cosmoshub plugin with github action

### ISSUE THREAD

**Issue by heejin-github** [dsrvlabs/vatz#270]
> - Parent : #236 

## Checklist

- [ ] New Feature for the Service/Plugin (Vatz)
- [x] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. such as Ex. I'm always frustrated

### **Describe the solution you'd like| Ex**
> A clear and concise description of what you want to happen

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

### **Additional context or comment**
> Add any other context or screenshots about the feature request here

- Vatz Plugin is using private repo, So I will process when private repo change public.

**Comment by xellos00** [comment]
all the official repos are change to public and now its all accessible from public. 
Now close this issue.
