### ISSUE TITLE
Enhance Make Command format

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#283]
## Checklist

- [ ] New Feature for the Service/Plugin (Vatz)
- [x] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. such as Ex. I'm always frustrated

Currently make command show fatal:message  such as 

```
 make build
fatal: No names found, cannot describe anything.
go build -ldflags="-X 'main.Version=main' -X 'main.Commit=d9c1036'" -v
```

```
 make test     
fatal: No names found, cannot describe anything.
=== RUN   TestInitCmd
2022-10-18T20:42:32-05:00 INF init module=main
2022-10-18T20:42:32-05:00 INF create file default.yaml module=main
2022-10-18T20:42:32-05:00 INF init module=main
2022-10-18T20:42:32-05:00 INF create file hello.yaml module=main
```

### **Describe the solution you'd like| Ex**
> A clear and concise description of what you want to happen

1. No fatal Message
2. Description for execute commands

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

### **Additional context or comment**
> Add any other context or screenshots about the feature request here.

<img width="568" alt="image" src="https://user-images.githubusercontent.com/6308023/196577548-bf42f2ac-72ef-4773-b3f6-cc21484aba08.png">
<img width="595" alt="image" src="https://user-images.githubusercontent.com/6308023/196577568-87bee250-6b55-4a78-a816-98c4fae09182.png">

**Comment by rootwarp** [comment]
Relates #403

close.
