### ISSUE TITLE
Feature Request - add more guides to installation.md 

### ISSUE THREAD

**Issue by qkrybin** [dsrvlabs/vatz#309]
## Checklist
- [ ] New Feature for the SVC/Plugin
- [ ] New Feature for CI/CD
- [ ] Enhancement on Vatz
- [x] Others(etc. e.g, documentation,...)
---

### **Please describe, what it's about or related Problem with**
It would be nice if we can add more guides to start.

### **Describe the output that you are expecting for above**
It would be great if these two parts were included in the installation guide.
- configure yaml
https://app.gitbook.com/o/-MiyxU38etxprZxihBZS/s/-Mj3CwiN6vyRfTZC-Ljw/general/contents/vatz_setup_guide#5.-configure-your-yaml
- starting command
https://app.gitbook.com/o/-MiyxU38etxprZxihBZS/s/-Mj3CwiN6vyRfTZC-Ljw/general/contents/vatz_setup_guide#5.-start-service-with-following-command

And also, I would like to suggest adding Plugin repo links according to their use in the installation.md too. It may be hard to know which plugins exist. 

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

### **Additional context**
> Add any other context or screenshots about the feature request here.

**Comment by xellos00** [comment]
@qkrybin 
just out of curiosity, Did you miss to read https://github.com/dsrvlabs/vatz/blob/main/docs/contributing.md?
or 
do we need update that docs as well?
I fully open to your feedback, let me know.

**Comment by qkrybin** [comment]
@xellos00 
I read that and contribution.md was understandable, sorry for missing infos!
However, I have one question about adding infos. sorry if it's a fool question, what is the difference between label enhancement and feature-development(or feature-request)? 



And in this issue, I just want to add a guide for writing yaml file on installation.md cause I was a bit confused. 😓

**Comment by xellos00** [comment]
@heejin-github @qkrybin 
Please, confirm up and running message is on logs in cosmos plugin.

**Comment by qkrybin** [comment]
> @heejin-github @qkrybin Please, confirm up and running message is on logs in cosmos plugin.

👍
```
2022-11-25T14:50:37+09:00 DBG block height increasing module=plugin
2022-11-25T14:51:07+09:00 INF Execute module=grpc
2022-11-25T14:51:07+09:00 INF previous block height: 13272098, latest block height: 13272344 module=plugin
```

**Comment by xellos00** [comment]
@qkrybin 
Can I close this issue?

**Comment by xellos00** [comment]
> @qkrybin Can I close this issue?

I will close this issue, if there's any need to another documentation, I will create another issue.
