### ISSUE TITLE
Update contributing.md

### ISSUE THREAD

**Issue by qkrybin** [dsrvlabs/vatz#325]
## Checklist
- [ ] New Feature for the SVC/Plugin
- [ ] New Feature for CI/CD
- [ ] Enhancement on Vatz
- [x] Others(etc. e.g, documentation,...)
---

### **Please describe, what it's about or related Problem with**
I created PR to update installation.md, but rejected because I made a branch under vatz repo.
contributing.md lack of guide about PR. 
https://github.com/dsrvlabs/vatz/pull/315 

### **Describe the output that you are expecting for above**

including more rules in PR policy
- fork vatz to the personal repo first, and make a branch under forked one.
- then PR to merge the branch 
- delete after

### **Additional context**
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/63234878/206125676-99ce18af-9f68-4515-a545-120712da97d1.png">

**Comment by qkrybin** [comment]
@xellos00 
Are there rules to merge PR?
for example, 
- how many people should review it?
- who should I get approval from?

**Comment by xellos00** [comment]
> @xellos00 Are there rules to merge PR? for example,
> 
> * how many people should review it? 2 people
> * Who is responsible for reviewing it? All Validator Team
> * who should I get approval from? Any 2 people one who approve it.

**Comment by qkrybin** [comment]
thanks! 
I was thinking that more rules are needed for other source developers, but I just realized that it's only for the internal(validator team) Do external and Internal processes have many differences?

**Comment by xellos00** [comment]
> Do external and Internal processes have many differences?

Currently, We do not have an external process yet and we need to settle. 
I still fully open to any suggestion.

**Comment by xellos00** [comment]
> thanks! I was thinking that more rules are needed for other source developers, but I just realized that the current process is only for the internal(validator team) Do external and Internal processes have many differences?

@qkrybin 
Can you get rid of external process part? 
I think it's better to get rid of it for now, because there's no internal or external.

**Comment by xellos00** [comment]
I will create another issue, if there's any need to update contribution.md
