### ISSUE TITLE
Cosmos - Plugin - Governance alarm

### ISSUE THREAD

**Issue by skonhwang** [dsrvlabs/vatz#326]
> - parent : #236 

Tasks
- Governance alarm
    - [x] New governance
    - [x] Answer of voter 
- [ ] Test code

- https://github.com/dsrvlabs/vatz-plugin-cosmoshub/pull/25

**Comment by skonhwang** [comment]
## Cosmos
![image](https://user-images.githubusercontent.com/106724973/206142953-2ba3b033-a12a-41f7-8c0c-30656d65e906.png)<br>

## Stargaze
![image](https://user-images.githubusercontent.com/106724973/206143061-d6d71c2b-b723-4778-ad87-6bd5fc3a542c.png)<br>

**Comment by xellos00** [comment]
only Test Code left

**Comment by xellos00** [comment]
@skonhwang 
Do you have any update for this? 
I think current cosmos plugin works properly to get a governance alarm. 
Please, let me know if there's anything.
