### ISSUE TITLE
Sysutil - plugin - cannot recover from alert status

### ISSUE THREAD

**Issue by heejin-github** [dsrvlabs/vatz#327]
- Related: #336

---

### Checklist
- [ ] Bug from Service (Vatz)
- [x] Bug from Plugin (Vatz) 
- [ ] Malfunction on CI/CD 
- [ ] etc(e.g, Hardware version doesn't match, )

---

### **Describe the bug**
> A clear and concise description of what the bug is.
cannot recover disk monitor alert.

### **How to Reproduce**
> Steps to reproduce the behavior:
1. use disk space over warning or critical level.
2. secure free space under warning or critical level.
3. check alert status

### **Expected behavior**
> A clear and concise description of what you expected to happen.
alert should be cleard after alert condition resolved.

### **Screenshots**
> If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/83936146/206152969-2cff3cc2-526c-4a14-9907-e4a082d5a165.png)

**Comment by heejin-github** [comment]
## disk monitor cannot recover from alert status
<img width="975" alt="image" src="https://user-images.githubusercontent.com/83936146/206152756-60b95091-eb0e-43a4-9fbc-25a208d6befb.png">

even if we have enough disk space under warning or critical level alert didn't recover to normal status.

**Comment by xellos00** [comment]
As mentioned in #336 
Recovery Flag is 
- STATE: SUCCESS
- SEVERITY: INFO

**Comment by heejin-github** [comment]
## Upload PR for this issue
- https://github.com/dsrvlabs/vatz-plugin-sysutil/pull/7
