### ISSUE TITLE
Cosmos - Plugin - Missed block 

### ISSUE THREAD

**Issue by gnongs** [dsrvlabs/vatz#329]
- Parents: none

## Checklist

- [x] New Feature for the Service/Plugin (Vatz)
- [ ] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. such as Ex. I'm always frustrated

Check the data on the block to see if our Validator is signing normally, and if it does not, it is considered as a miss block and an alert is generated.

### **Describe the solution you'd like| Ex**
> A clear and concise description of what you want to happen

Alert occurs if more than a certain number of signals are not made out of the last 100 blocks.

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

### **Additional context or comment**
> Add any other context or screenshots about the feature request here.

**Comment by xellos00** [comment]
@gnongs 
Do you have any update for this issue?

**Comment by gnongs** [comment]
> @gnongs Do you have any update for this issue?

No I don't have any update 😥

**Comment by xellos00** [comment]
> > @gnongs Do you have any update for this issue?
> 
> 
> 
> @xellos00 No I don't have any update 😥

ok, let's find out schedule for this issue together.

**Comment by xellos00** [comment]
@gnongs 
Give me feedback whether this issue can handle within next 2 weeks.

**Comment by gnongs** [comment]
@xellos00 It seems difficult to do the work in two weeks. So it looks good to exclude the plug-in.

**Comment by xellos00** [comment]
@gnongs 
let's close this issue, and open again if there's any need.
Please, close this issue, if you don't have any concern with it.
