### ISSUE TITLE
Unable to repeat different warnings

### ISSUE THREAD

**Issue by kim201212** [dsrvlabs/vatz#333]
### Checklist
- [x] Bug from Service (Vatz)
- [ ] Bug from Plugin (Vatz) 
- [ ] Malfunction on CI/CD 
- [ ] etc(e.g, Hardware version doesn't match, )

---

### **Describe the bug**
> A clear and concise description of what the bug is.

The second warning does not come when different warnings are came consecutively.
Assume monitoring validators from 1 to 9.
If validator 1 missed the block in block 10 and validator 2 missed the block in block 11, a warning alert can occur consecutively.
It's not possible at the moment. I think we should give it a chance to choise.

### **How to Reproduce**
> Steps to reproduce the behavior:

1. Other warnings occur consecutively.
2. Only the first warning appeared.

### **Expected behavior**
> A clear and concise description of what you expected to happen.

Different warnings should appear.

### **Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by kim201212** [comment]
I think we should add `msg` to `StateFlag` and compare whether `msg` is the same.

**Comment by xellos00** [comment]
> I think we should add `msg` to `StateFlag` and compare whether `msg` is the same. What do you think @xellos00 ?

Can you put your default.yaml file on here? 
and can you specify how did you find this error? 
in fact, it's hard for me to understand what you've describe above.

**Comment by hqueue** [comment]
@kim201212 I've question about this issue.

> If validator 1 missed the block in block 10 and validator 2 missed the block in block 11, a warning alert can occur consecutively.
It's not possible at the moment. I think we should give it a chance to choose.

What do you mean by this alert (miss alert)?
This type of alert is completely different from other alerts.
For example

- Block height alert:  if block height is not increased for a while, alert is fired. When block increases again, alert is resolved.

- Block miss alert for validator 1: If validator 1 missed the block 10, alert fired. 
   - @kim201212 Then when this alert is resolved? If there is no condition for resolution, then it seems it's not an alert because it can not be resolved. 

Let's discuss this together in face :)

**Comment by xellos00** [comment]
@kim201212 
Please, give back ground info and comment how VATZ has to be behave to resolve this issue.

**Comment by kim201212** [comment]
No new Severity needs to be added. 
We put the repeat flag in the yaml file, and add the repeat flag to the message.

**Comment by xellos00** [comment]
> No new Severity needs to be added. We put the repeat flag in the yaml file, and add the repeat flag to the message.

for more details, current VATZ has using following flags for notification through dispatchers
> refer to 
> - [plugin.proto](https://github.com/dsrvlabs/vatz-proto/blob/main/proto/vatz/plugin/v1/plugin.proto)
> - [dispatcher.go](https://github.com/dsrvlabs/vatz/blob/main/manager/dispatcher/dispatcher.go)
- STATE
- SEVERITY

In previous discussion 
- Give optional parameter to set different behaviors
from 
```
func messageHandler(isFirst bool, preStat tp.StateFlag, info tp.NotifyInfo) (bool, tp.Reminder, tp.ReqMsg) {
...
``` 
to 
```
func messageHandler(isFirst bool, preStat tp.StateFlag, info tp.NotifyInfo, options opt) (bool, tp.Reminder, tp.ReqMsg) {
...
```

**Comment by xellos00** [comment]
@kim201212 
It's been a while, Let me know your progress with it. 
let me know If you don't think you would finish this any time soon.
