### ISSUE TITLE
Update Codes to pass Golint 

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#344]
## Checklist

- [ ] New Feature for the Service/Plugin (Vatz)
- [x] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. such as Ex. I'm always frustrated

### **Describe the solution you'd like| Ex**
> A clear and concise description of what you want to happen

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

### **Additional context or comment**
> Add any other context or screenshots about the feature request here.

**Comment by xellos00** [comment]
@gnongs, @kim201212 
Does any of you would like to handle this issue? 
let me know if there's other issue that you would like to take over.

**Comment by kim201212** [comment]
> @gnongs, @kim201212 Does any of you would like to handle this issue? let me know if there's other issue that you would like to take over.

- https://github.com/dsrvlabs/vatz/pull/311
- Is the above PR not enough??

**Comment by xellos00** [comment]
> > @gnongs, @kim201212 Does any of you would like to handle this issue? let me know if there's other issue that you would like to take over.
> 
> * [Add github action golangci-lint  #311](https://github.com/dsrvlabs/vatz/pull/311)
> * Is the above PR not enough?
> * Is it okay to update all at once?

I missed to put the background, currently every PR fails due to go-lint filter such as

**Comment by kim201212** [comment]
@xellos00 I will handle this issue, but I think golangci-lint is working well.
We need to fix vatz code so that it passes the lint ci.

**Comment by xellos00** [comment]
@xellos00 
Create sub-issue for module!

**Comment by xellos00** [comment]
@kim201212 
How's going for this issue? progeress?

**Comment by kim201212** [comment]
> @kim201212 How's going for this issue? progeress?

I thought you will separate the module for me.
Can I just arbitrarily choose a module?

**Comment by xellos00** [comment]
> > @kim201212 How's going for this issue? progeress?
> 
> I thought you will separate the module for me. Can I just arbitrarily choose a module?

yeah, go ahead, and I also think it's a time to wrap this up. 
Can you finish this anytime soon, but I hope you to finish this at most by end of this month.

**Comment by xellos00** [comment]
@kim201212 
This is final reminder, 
Let me know if you don't want finish this issue.

**Comment by xellos00** [comment]
> @kim201212 This is final reminder, Let me know if you don't want finish this issue.

@kim201212 
Any update?
