### ISSUE TITLE
Vatz-bot - Token management

### ISSUE THREAD

**Issue by hqueue** [dsrvlabs/vatz#347]
- Parents: https://github.com/dsrvlabs/vatz/issues/385

---

### **What does it require to on Vatz**
> A clear and concise description of what you expected to happen through Ci/CD

This issue will track the history of token from @vatzDSRV `vatz-bot`.

### **Expected behavior**
> A clear and concise description of results after CI/CD implementation.

### **How to run**
> Please, Update and give simple guide to run CI/CD process with this issue. 

### **Screenshots**
> If applicable, add screenshots to help explain your problem

**Comment by hqueue** [comment]
@xellos00 It seems token from @vatzDSRV will be expired in a few days.
Let's me know what to do.

1) re-generate the token
2) generate a whole new token

**Comment by xellos00** [comment]
> @xellos00 It seems token from @vatzDSRV will be expired in a few days. Let's me know what to do.
> 
> 1. re-generate the token
> 2. generate a whole new token

I will generate a whole new token on our meeting at 12/27/2022 11:00 +09:00:00

**Comment by xellos00** [comment]
> > @xellos00 It seems token from @vatzDSRV will be expired in a few days. Let's me know what to do.
> > 
> > 1. re-generate the token
> > 2. generate a whole new token
> 
> I will generate a whole new token on our meeting at 12/27/2022 11:00 +09:00:00

@hqueue 
I generated a new-token which is valid until End of March 2023

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/6308023/210042646-b2813389-8220-424e-9b5e-dabea0db2d38.png">

**Comment by xellos00** [comment]
@xellos00 I will Create a Token management Issue for this as Good first Issue.

**Comment by xellos00** [comment]
We can close this issue.
