### ISSUE TITLE
Documentation for VATZ beta version

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#349]
## Checklist

- [ ] New Feature for the Service/Plugin (Vatz)
- [ ] Enhancement (Vatz)
- [x] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. such as Ex. I'm always frustrated

### **Describe the solution you'd like| Ex**
> A clear and concise description of what you want to happen

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

### **Additional context or comment**
> Add any other context or screenshots about the feature request here.

**Comment by xellos00** [comment]
@qkrybin 
Can you create an issue for followings and commit it. 
- Update  README.md on VATZ
   - Please, ping me if you are not sure, (just comment it and I will fix it)
   - Contact list for DSRV Labs
- Review & Review 
   - Installation Guide & How to Start
   - Contributing Gudie

**Comment by xellos00** [comment]
@rootwarp 
Can you create an issue for followings
- doc for simple guide for VATZ CLIs

**Comment by xellos00** [comment]
@gnongs 
Can you create an issue for followings  and commit it
- overall background node exporter and brief explanation.

**Comment by rootwarp** [comment]
> @rootwarp Can you create an issue for followings and commit it
> 
> * doc for simple guide for VATZ CLIs

Create at https://github.com/dsrvlabs/vatz/issues/350.

**Comment by gnongs** [comment]
> @gnongs Can you create an issue for followings and commit it
> 
> * overall background node exporter and brief explanation.

@xellos00 Created! - #353

**Comment by qkrybin** [comment]
> @qkrybin Can you create an issue for followings and commit it.
> 
> * Update  README.md on VATZ
>   
>   * Please, ping me if you are not sure, (just comment it and I will fix it)
>   * Contact list for DSRV Labs

@xellos00 Create an issue for updating readme.md first. #354

**Comment by xellos00** [comment]
Tasks
- [ ] #350 
- [ ] #353 
- [ ] #354
