### ISSUE TITLE
Tagging for beta version of VATZ and official plugins

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#351]
## Checklist
- [ ] New Feature for the SVC/Plugin
- [ ] New Feature for CI/CD
- [ ] Enhancement on Vatz
- [x] Others(etc. e.g, documentation,...)
---

This is  Pre-version for first beta release of VATZ.

**Comment by xellos00** [comment]
## Agenda 

> Sample
> https://github.com/shentufoundation/shentu/releases/tag/v2.6.0
- Tags, v0.1-beta1
- Tags, v0.2-beta2


---

**Comment by xellos00** [comment]
@xellos00 @heejin-github 


# Progress to next Friday
RC-Branch
- v1.0-beta-rc.1
   - [ ] VATZ
   - [ ] vatz-plugin-sysutil
   - [ ] vatz-plugin-cosmoshub 

- TEST

- Release Beta

**Comment by heejin-github** [comment]
## Test Protocols
Please test vatz and all vatz plugins in v1.0-beta-rc.1
https://github.com/dsrvlabs/vatz/tree/v1.0-beta-rc.1
https://github.com/dsrvlabs/vatz-plugin-sysutil/tree/v1.0-beta-rc.1
https://github.com/dsrvlabs/vatz-plugin-cosmoshub/tree/v1.0-beta-rc.1

- @meetrick : Sei
- @heejin-github : Provenance, Assetmantle, Crescent
- @kim201212 : Axelar, Persistence
- @skonhwang : Cosmoshub, Injective, Stargaze
- @gnongs : Agoric

**Comment by meetrick** [comment]
# 황제 - sei-project
- https://github.com/dsrvlabs/sei-project/issues/48

**Comment by skonhwang** [comment]
## cosmoshub plugin - node_peer_count
- The port of tendermint was fixed by `26657`, so I modified that user can set tendermint port
- https://github.com/dsrvlabs/stargaze-project/issues/26#issuecomment-1369391268

**Comment by gnongs** [comment]
## Agoric
- issue: https://github.com/dsrvlabs/agoric-project/issues/145

**Comment by heejin-github** [comment]
- https://github.com/dsrvlabs/crescent-project/issues/47
- https://github.com/dsrvlabs/assetmantle-project/issues/21
-

**Comment by heejin-github** [comment]
## panic on healthcheck 
- if vatz config have abnormal configuration for pagerduty, panic happened when the healthcheck occurred.

- config
```
    dispatch_channels:
      - channel: "discord"
        secret: 
      - channel: "pagerduty"
        secret: "Put your PagerDuty's Integration Key (Events API v2)"
```

- log
```
panic: interface conversion: interface {} is nil, not string

goroutine 211 [running]:
github.com/dsrvlabs/vatz/manager/dispatcher.(*pagerduty).SendNotification(0xc000082f00, {{0xcb0908, 0xf}, 0x3, {0xcb08f9, 0xf}, 0x4, {0xca7deb, 0x4}, 0x0})
        /root/git/vatz/manager/dispatcher/pagerduty.go:41 +0xba5
github.com/dsrvlabs/vatz/manager/healthcheck.(*healthChecker).VATZHealthCheck.func1()
        /root/git/vatz/manager/healthcheck/general_healthcheck.go:87 +0xf4
github.com/robfig/cron/v3.FuncJob.Run(0xc0000577d0?)
        /usr/local/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x1a
github.com/robfig/cron/v3.(*Cron).startJob.func1()
        /usr/local/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x6a
created by github.com/robfig/cron/v3.(*Cron).startJob
        /usr/local/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xad

```

- https://github.com/dsrvlabs/vatz/blob/v1.0-beta-rc.1/manager/healthcheck/general_healthcheck.go#L82-L88
```
func (h *healthChecker) VATZHealthCheck(healthCheckerSchedule []string, dispatchers []dp.Dispatcher) error {
	c := cron.New(cron.WithLocation(time.UTC))
	for i := 0; i < len(healthCheckerSchedule); i++ {
		c.AddFunc(healthCheckerSchedule[i], func() {
			for _, dispatcher := range dispatchers {
				dispatcher.SendNotification(h.healthMSG)
			}
```

- https://github.com/dsrvlabs/vatz/blob/v1.0-beta-rc.1/manager/dispatcher/pagerduty.go#L41
```
func (p *pagerduty) SendNotification(msg tp.ReqMsg) error {

	var (
		pagerdutySeverity string
		emoji             string
		methodName        = msg.Options["pUnique"].(string)
	)

```

**Comment by heejin-github** [comment]
> ## panic on healthcheck
> * if vatz config have abnormal configuration for pagerduty, panic happened when the healthcheck occurred.
> * config
> 
> ```
>     dispatch_channels:
>       - channel: "discord"
>         secret: 
>       - channel: "pagerduty"
>         secret: "Put your PagerDuty's Integration Key (Events API v2)"
> ```
> 
> * log
> 
> ```
> panic: interface conversion: interface {} is nil, not string
> 
> goroutine 211 [running]:
> github.com/dsrvlabs/vatz/manager/dispatcher.(*pagerduty).SendNotification(0xc000082f00, {{0xcb0908, 0xf}, 0x3, {0xcb08f9, 0xf}, 0x4, {0xca7deb, 0x4}, 0x0})
>         /root/git/vatz/manager/dispatcher/pagerduty.go:41 +0xba5
> github.com/dsrvlabs/vatz/manager/healthcheck.(*healthChecker).VATZHealthCheck.func1()
>         /root/git/vatz/manager/healthcheck/general_healthcheck.go:87 +0xf4
> github.com/robfig/cron/v3.FuncJob.Run(0xc0000577d0?)
>         /usr/local/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136 +0x1a
> github.com/robfig/cron/v3.(*Cron).startJob.func1()
>         /usr/local/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312 +0x6a
> created by github.com/robfig/cron/v3.(*Cron).startJob
>         /usr/local/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:310 +0xad
> ```
> 
> * https://github.com/dsrvlabs/vatz/blob/v1.0-beta-rc.1/manager/healthcheck/general_healthcheck.go#L82-L88
> 
> ```
> func (h *healthChecker) VATZHealthCheck(healthCheckerSchedule []string, dispatchers []dp.Dispatcher) error {
> 	c := cron.New(cron.WithLocation(time.UTC))
> 	for i := 0; i < len(healthCheckerSchedule); i++ {
> 		c.AddFunc(healthCheckerSchedule[i], func() {
> 			for _, dispatcher := range dispatchers {
> 				dispatcher.SendNotification(h.healthMSG)
> 			}
> ```
> 
> * https://github.com/dsrvlabs/vatz/blob/v1.0-beta-rc.1/manager/dispatcher/pagerduty.go#L41
> 
> ```
> func (p *pagerduty) SendNotification(msg tp.ReqMsg) error {
> 
> 	var (
> 		pagerdutySeverity string
> 		emoji             string
> 		methodName        = msg.Options["pUnique"].(string)
> 	)
> ```

We should add Options for `HealthMsg`.
- https://github.com/dsrvlabs/vatz/blob/main/manager/healthcheck/healthcheck.go#L21-L31
```
func GetHealthChecker() HealthCheck {
	healthCheckerOnce.Do(func() {
		healthCheckerSingle = healthChecker{
			healthMSG: tp.ReqMsg{
				FuncName:     "VATZHealthCheck",
				State:        pluginpb.STATE_SUCCESS,
				Msg:          "VATZ is Alive!!",
				Severity:     pluginpb.SEVERITY_INFO,
				ResourceType: "VATZ",
				Options: <Add Options Here>
			},
			pluginStatus: sync.Map{},


```

**Comment by xellos00** [comment]
@heejin-github 
@xellos00 

# Sample template for the Release

## VATZ

{Private wording}

Learn more about how `VATZ` plugins are working at 

----
## vatz-plugin-sysutil

Plugins
- `cpu_monitor` : monitor CPU utilization
- `disk_monitor` : monitor disk space utilization
- `mem_monitor` : monitor memory utilization

>  Please refer to https://github.com/ShentuChain/mainnet/tree/main/shentu-2.2/upgrades#v260-upgrade for installation and usage instructions.

**Comment by xellos00** [comment]
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/6308023/211110557-daa6259f-26e8-462a-9cc5-869e57dc02ec.png">

**Comment by xellos00** [comment]
@dsrvlabs/validator 

Thanks Everyone. 
We made beta release.
