### ISSUE TITLE
Update README.md on VATZ

### ISSUE THREAD

**Issue by qkrybin** [dsrvlabs/vatz#354]
## Checklist

- [ ] New Feature for the Service/Plugin (Vatz)
- [ ] Enhancement (Vatz)
- [x] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. such as Ex. I'm always frustrated

### **Describe the solution you'd like| Ex**
> A clear and concise description of what you want to happen

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

### **Additional context or comment**
> Add any other context or screenshots about the feature request here.

**Comment by qkrybin** [comment]
@xellos00 
Readme.md contains the mission. I wonder if it's only for VATZ or if it needs to be revised according to DSRV's new mission. 
```
**Our Mission**
We're on a mission to transform the way people experience blockchain technology and let them contribute and become a part of its technology. As Validators, we provide tools to people to manage their own nodes with low cost and less effort for anyone who would like to join future blockchain technology.
```

**Comment by qkrybin** [comment]
@xellos00 
Is this roadmap still valid and correct?

- Data Analysis:  **VATZ** helps to build datasets for your managing protocols and transfer your data into popular services Prometheus, Kafaka, Google BigQuery and more. Because of this, VATZ aims to set your Node infrastructure as efficiently as possible, and operators get insight into dependencies in their infrastructure. (2023-Q3)
- Change automation:  Complex sets of node's operational tasks can be done through **VATZ** with minimal human interaction. (2023-Q2)

**Comment by xellos00** [comment]
> @xellos00 Is this roadmap still valid and correct?
> 
> * Data Analysis:  **VATZ** helps to build datasets for your managing protocols and transfer your data into popular services Prometheus, Kafaka, Google BigQuery and more. Because of this, VATZ aims to set your Node infrastructure as efficiently as possible, and operators get insight into dependencies in their infrastructure. (2023-Q3)
> * Change automation:  Complex sets of node's operational tasks can be done through **VATZ** with minimal human interaction. (2023-Q2)

You can ignore it from README.md for now, 
I will take care once you raise PR request.
