### ISSUE TITLE
Pinning the Project on DSRV public repositories. 

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#398]
- Parents: #395 

## Checklist
- [ ] New Feature for the SVC/Plugin
- [ ] New Feature for CI/CD
- [ ] Enhancement on Vatz
- [x] Others(etc. e.g, documentation,...)
---

### **Please describe, what it's about or related Problem with**
> A clear description of what feature need to be developed or enhanced in Vatz 

There's chance to advertise and make people to access more on VATZ repo. 

<img width="889" alt="image" src="https://user-images.githubusercontent.com/6308023/216730313-a637483e-e173-4688-b4c2-66af82218c44.png">

**Comment by xellos00** [comment]
As we voted in previous VATZ weekly meeting, 
we decided to put current repo to pin on DSRV repo. 

@hqueue 
Can you put VATZ repo on DSRV Labs?

**Comment by hqueue** [comment]
@xellos00 Pined `vatz` :)


## Public

<img width="823" alt="image" src="https://user-images.githubusercontent.com/9247907/216873858-0e1c45b4-0d11-416b-8517-2512bf00e139.png">

## Member(Private)

<img width="925" alt="image" src="https://user-images.githubusercontent.com/9247907/216874160-7483e88e-1ff8-4023-9c84-89a8f96236d6.png">
