### ISSUE TITLE
Cosmos - Plugin - node_is_alive

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#401]
### Checklist
- [ ] Bug from Service (Vatz)
- [x] Bug from Plugin (Vatz) 
- [ ] Malfunction on CI/CD 
- [ ] etc(e.g, Hardware version doesn't match, )

---

### **Describe the bug**
> A clear and concise description of what the bug is.

### **How to Reproduce**
> Steps to reproduce the behavior:

2. '...'

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/6308023/217409661-779a1dd5-2115-470d-a4f7-b241e6584d4c.png">

@dsrvlabs/validator 
Ping @xellos00  if you need further info about this. 

### **Expected behavior**
> A clear and concise description of what you expected to happen.

### **Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by heejin-github** [comment]
```
2023-01-25T17:48:02Z INF Execute module=grpc
2023-01-25T17:48:02Z ERR Get "http://localhost:26657/health": dial tcp: lookup localhost: device or resource busy Response=Error
2023-01-25T17:48:02Z ERR Get "http://localhost:26657/health": dial tcp: lookup localhost: device or resource busy GetHealth=Error
2023-01-25T17:48:32Z INF Execute module=grpc
2023-01-25T17:48:32Z ERR Get "http://localhost:26657/health": dial tcp: lookup localhost: device or resource busy Response=Error
2023-01-25T17:48:32Z ERR Get "http://localhost:26657/health": dial tcp: lookup localhost: device or resource busy GetHealth=Error
2023-01-25T17:49:02Z INF Execute module=grpc
2023-01-25T17:49:02Z ERR Get "http://localhost:26657/health": dial tcp: lookup localhost: device or resource busy Response=Error
2023-01-25T17:49:02Z ERR Get "http://localhost:26657/health": dial tcp: lookup localhost: device or resource busy GetHealth=Error
2023-01-25T17:49:07Z INF Shutting down module=grpc
2023-01-25T17:49:07Z INF Stop module=grpc
```

**Comment by xellos00** [comment]
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/6308023/225334264-622725dc-1a83-4584-bcbb-c894d6883053.png">

**Comment by heejin-github** [comment]
@xellos00 , @meetrick 
Could you please test with rpc endpoint `http://127.0.0.1:26657` ?
You can run the `node_is_alive` plugin with `-rpcAddr` argument.
```
# node_is_alive -rpcAddr http://127.0.0.1:26657 >> <LOG_FILE_NAME> 2>&1 &
or
# vatz plugin start -p <YOUR_PLUGIN_NAME> -a "-rpcAddr http://127.0.0.1:26657" -l <LOG_FILE_NAME>
```

**Comment by xellos00** [comment]
> @xellos00 , @meetrick Could you please test with rpc endpoint `http://127.0.0.1:26657` ? You can run the `node_is_alive` plugin with `-rpcAddr` argument.
> 
> ```
> # node_is_alive -rpcAddr http://127.0.0.1:26657 >> <LOG_FILE_NAME> 2>&1 &
> or
> # vatz plugin start -p <YOUR_PLUGIN_NAME> -a "-rpcAddr http://127.0.0.1:26657" -l <LOG_FILE_NAME>
> ```

Yeah, I Started again, Let's check how it's working if there's no error such as above. 
We need to update 127.0.0.1 as default setting in the plugin 
- https://github.com/dsrvlabs/certik-project/issues/137

**Comment by xellos00** [comment]
@heejin-github 
I am still getting same error, Do you have any suggestion?

**Comment by heejin-github** [comment]
> @heejin-github I am still getting same error, Do you have any suggestion?

I think it might have insufficient open file limit. it is only 1024 in current.
please help to test after increase open file limit on your machine.
- log
```
2023-03-20T16:03:55Z INF Execute module=grpc
2023-03-20T16:03:55Z ERR Get "http://127.0.0.1:26657/health": dial tcp 127.0.0.1:26657: socket: too many open files Response=Error
2023-03-20T16:03:55Z ERR Get "http://127.0.0.1:26657/health": dial tcp 127.0.0.1:26657: socket: too many open files GetHealth=Error
```
- ulimit
```
# ulimit -n
1024
```

**Comment by xellos00** [comment]
> > @heejin-github I am still getting same error, Do you have any suggestion?
> 
> I think it might have insufficient open file limit. it is only 1024 in current. please help to test after increase open file limit on your machine.
> 
> * log
> 
> ```
> 2023-03-20T16:03:55Z INF Execute module=grpc
> 2023-03-20T16:03:55Z ERR Get "http://127.0.0.1:26657/health": dial tcp 127.0.0.1:26657: socket: too many open files Response=Error
> 2023-03-20T16:03:55Z ERR Get "http://127.0.0.1:26657/health": dial tcp 127.0.0.1:26657: socket: too many open files GetHealth=Error
> ```
> 
> * ulimit
> 
> ```
> # ulimit -n
> 1024
> ```

I've updated,  let see how it's going 
- https://github.com/dsrvlabs/certik-project/issues/137

**Comment by xellos00** [comment]
> > > @heejin-github I am still getting same error, Do you have any suggestion?
> > 
> > 
> > I think it might have insufficient open file limit. it is only 1024 in current. please help to test after increase open file limit on your machine.
> > 
> > * log
> > 
> > ```
> > 2023-03-20T16:03:55Z INF Execute module=grpc
> > 2023-03-20T16:03:55Z ERR Get "http://127.0.0.1:26657/health": dial tcp 127.0.0.1:26657: socket: too many open files Response=Error
> > 2023-03-20T16:03:55Z ERR Get "http://127.0.0.1:26657/health": dial tcp 127.0.0.1:26657: socket: too many open files GetHealth=Error
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * ulimit
> > 
> > ```
> > # ulimit -n
> > 1024
> > ```
> 
> I've updated, let see how it's going
> 
> * [Shentu(Certik) VATZ Upgrade with Logs certik-project#137](https://github.com/dsrvlabs/certik-project/issues/137)

There's no more error since last week
- https://github.com/dsrvlabs/certik-project/issues/137

**Comment by heejin-github** [comment]
Close this issue.
add trouble shooting guide for this case in README.
- https://github.com/dsrvlabs/vatz-plugin-cosmoshub/blob/main/README.md#troubleshooting
