### ISSUE TITLE
Follow up progress for VATZ's official icons

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#405]
## Checklist

- [ ] New Feature for the Service/Plugin (Vatz)
- [ ] Enhancement (Vatz)
- [x] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. such as Ex. I'm always frustrated

<img width="593" alt="image" src="https://user-images.githubusercontent.com/6308023/218008630-f57fe214-2a06-4d39-862e-3435f7e15c50.png">

Current icon of VATZ project isn't designed for the VATZ project. 
As we discussed in weekly meeting, we requested VATZ on official icons to  @Jihoo-Designer
I will share this issue to @Jihoo-Designer

### **Describe the solution you'd like| Ex**
> A clear and concise description of what you want to happen

I will keep update progress about icon, but its priority is low and can't push @Jihoo-Designer. 

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

**Comment by Jihoo-Designer** [comment]
안녕하세요, 동요님! 

VATZ 아이콘 이미지 시안과 샘플 공유드립니다. 


### **VATZ 아이콘**
![vatz-icon-2023-02-11](https://user-images.githubusercontent.com/62600058/218184420-4aedcaff-704e-4f02-94dd-1803b08e70af.png)

- Validator 팀이 사용하시는 아이콘과의 유사성/ 무게감에 따라 구분해두었습니다.
- **제가 가장 제안드리는 것은 2번**으로, 이유는 아래와 같습니다.
1. 팀 아이콘과 너무 비슷하지도 너무 다르지도 않아, 서로 구분하기 어렵지 않고 VATZ만의 아이덴티티를 보일 수 있음.
2. 무게감이 있어 다른 아이콘 사이에 있어도 충분히 존재감 있을 수 있음. ( V 글자가 자체가 굉장히 날렵해서 엣지있으면서 존재감을 내기 어렵더라구요)

- **나머지 시안에서 선택을 해주셔도 완전 괜찮습니다. 혹은 디벨롭 방향에 대한 제안이 있으시다면 편하게 말씀주세요!** 


### **샘플 이미지**
![vatz-icon-sample-2023-02-11](https://user-images.githubusercontent.com/62600058/218186279-b5c99003-815e-4182-9f48-f70f4974439b.png)

- 최종 아이콘이 선정되고 난 뒤, 작업파일을 어떻게 export 하여 전달드리면 좋을지 등에 대한 예시와 질문입니다.

1. **어떤 형식들이 필요하신지** 알려주세요! (예. 검정바탕에 심볼/ 투명바탕에 심볼+타이포/ 샘플에 없는 다른 것 등)
2. **이미지 크기/ 파일 용량 제한 등이 있는지** 알려주세요! 


감사합니다 :)

**Comment by xellos00** [comment]
1. 👍🏽 
2. ❤️ 
3. 😄 
4. 🎉 
5. 🚀 
6. 👀

**Comment by xellos00** [comment]
우상향!!!

**Comment by xellos00** [comment]
for README
1. left 👍🏽 
2. right ❤️ 
----

**Comment by xellos00** [comment]
For CLI version
1. left 👍🏽 
2. right ❤️

**Comment by xellos00** [comment]
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/6308023/220257373-cabdd6db-364d-4557-b440-adc5bd012a2e.png">

```
안녕하세요 동요님! 아침에 잠깐 미팅을 하느라 조금 늦어져 죄송합니다..!😢 

https://drive.google.com/drive/folders/103CpSX99HGa2AOGAluei0B3YLj14TkOi?usp=sharing 
위 구글 폴더에서 다운받으실 수 있도록 업로드 해두었으며, 

https://www.figma.com/file/YoGc04xNDG3ujrhz8KY1li/01.-Logo-(DSRV%2Bprotocol)?node-id=620%3A9&t=ho86nRVqo8r4KKek-1
저희 DSRV 피그마 로고파일 에도 업로드 해두었습니다! 

위 두 링크 모두 회사 이메일 계정으로 접속하셔야합니다!

늦게 전달드려 다시한번 죄송합니다, 
더 필요하신 파일이 있으시면 언제든 편히 말씀 주세요☺️
```
