### ISSUE TITLE
VATZ Service vulnerability

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#410]
### Checklist
- [ ] Bug from Service (Vatz)
- [ ] Bug from Plugin (Vatz) 
- [ ] Malfunction on CI/CD 
- [x] etc(e.g, Hardware version doesn't match, )

---

### **Describe the bug**
> A clear and concise description of what the bug is.

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/6308023/220200283-58ecfbac-14d3-4dde-8a2f-0f89cf3c7b49.png">

### **Expected behavior**
> A clear and concise description of what you expected to happen.

### **Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by xellos00** [comment]
- [ ] [dsrvlabs/vatz-plugin-mevboost](https://github.com/dsrvlabs/vatz-plugin-mevboost/security/dependabot/go.sum/golang.org%2Fx%2Fnet/open)
- [ ] [dsrvlabs/vatz-plugin-sysutil](https://github.com/dsrvlabs/vatz-plugin-sysutil/security/dependabot/go.sum/golang.org%2Fx%2Fnet/open)
- [ ] [dsrvlabs/vatz-proto](https://github.com/dsrvlabs/vatz-proto/security/dependabot/go.sum/golang.org%2Fx%2Fnet/open) 
- [ ] [dsrvlabs/vatz-plugin-cosmoshub](https://github.com/dsrvlabs/vatz-plugin-cosmoshub/security/dependabot/go.sum/golang.org%2Fx%2Fnet/open)
- [ ] [dsrvlabs/vatz](https://github.com/dsrvlabs/vatz/security/dependabot/sdk/go.sum/golang.org%2Fx%2Fnet/open)

**Comment by xellos00** [comment]
@skonhwang 
Can you check Task [#1](https://github.com/dsrvlabs/vatz-plugin-mevboost/security/dependabot?q=is%3Aopen+manifest%3Ago.sum+package%3Agolang.org%2Fx%2Fnet) ? 

@heejin-github 
Can you check Task? [#2](https://github.com/dsrvlabs/vatz-plugin-sysutil/security/dependabot?q=is%3Aopen+manifest%3Ago.sum+package%3Agolang.org%2Fx%2Fnet), [#4](https://github.com/dsrvlabs/vatz-plugin-cosmoshub/security/dependabot?q=is%3Aopen+manifest%3Ago.sum+package%3Agolang.org%2Fx%2Fnet)

**Comment by xellos00** [comment]
@heejin-github 
Can you check Task [#2](https://github.com/dsrvlabs/vatz-plugin-sysutil/security/dependabot?q=is%3Aopen+manifest%3Ago.sum+package%3Agolang.org%2Fx%2Fnet), [#4](https://github.com/dsrvlabs/vatz-plugin-cosmoshub/security/dependabot?q=is%3Aopen+manifest%3Ago.sum+package%3Agolang.org%2Fx%2Fnet) ?

**Comment by heejin-github** [comment]
> @heejin-github Can you check Task [#2](https://github.com/dsrvlabs/vatz-plugin-sysutil/security/dependabot?q=is%3Aopen+manifest%3Ago.sum+package%3Agolang.org%2Fx%2Fnet), [#4](https://github.com/dsrvlabs/vatz-plugin-cosmoshub/security/dependabot?q=is%3Aopen+manifest%3Ago.sum+package%3Agolang.org%2Fx%2Fnet) ?

- https://github.com/dsrvlabs/vatz-plugin-sysutil/pull/8
- https://github.com/dsrvlabs/vatz-plugin-cosmoshub/pull/29

**Comment by xellos00** [comment]
# dsrvlabs/vatz-proto

**Comment by skonhwang** [comment]
> @skonhwang
> Can you check Task [#1](https://github.com/dsrvlabs/vatz-plugin-mevboost/security/dependabot?q=is%3Aopen+manifest%3Ago.sum+package%3Agolang.org%2Fx%2Fnet) ?

- https://github.com/dsrvlabs/vatz-plugin-mevboost/pull/1
