### ISSUE TITLE
Building up new policy for Plugins to public and set up on the lists

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#415]
- Related: https://github.com/dsrvlabs/vatz/issues/462

---

- We do not have any policies that list up that plugins for users
- Requirements 
   - [x] [License](https://github.com/dsrvlabs/vatz/issues/415#issuecomment-1488052944)
      - GPL2
      - let team members know, if there's certain options available.   
   - [x] [Installation guide](https://github.com/dsrvlabs/vatz/issues/415#issuecomment-1488053105) 
   - [x] [Rules](https://github.com/dsrvlabs/vatz/issues/415#issuecomment-1488056507)

--- 
@xellos00 
- create documentation issue

Review 
@hqueue 
@qkrybin 
@rootwarp 
@meetrick

**Comment by xellos00** [comment]
# License

**Comment by xellos00** [comment]
# Installation guide

**Comment by xellos00** [comment]
# Rules

**Comment by qkrybin** [comment]
> * Template may include for followings
>   
>   * summary
>   * github address
>   * https://pkg.go.dev for version
>   * how to install
>     * md file link  for their repo

https://pkg.go.dev for version  @xellos00  Why is this needed?

**Comment by xellos00** [comment]
As discussed last bi-weekly meeting, we are going to mimic style in [go-ethereum](https://github.com/ethereum/go-ethereum#license) 

<img width="1075" alt="image" src="https://github.com/dsrvlabs/vatz/assets/6308023/3ce8df4c-5135-4de6-bafc-5b8b359ea22d">

**Comment by xellos00** [comment]
Difference between GPL2 and GPL3

<img width="867" alt="image" src="https://github.com/dsrvlabs/vatz/assets/6308023/2c1ce3ed-4dd4-41af-9e63-aa9c3dcf382b">
<img width="859" alt="image" src="https://github.com/dsrvlabs/vatz/assets/6308023/d9f8baf2-e9c4-44a7-b652-fc96d9f22d25">

**Comment by xellos00** [comment]
- GPL2 👍🏽 
- GPL3 ❤️ 

---

**Comment by xellos00** [comment]
- License is added 
   - #467 
- Documents is update as well
   - #472 
   - #452
