### ISSUE TITLE
Sysutil - Plugin - Network Monitoring

### ISSUE THREAD

**Issue by heejin-github** [dsrvlabs/vatz#423]
## Checklist
- [X] New Feature for the SVC/Plugin
- [ ] New Feature for CI/CD
- [ ] Enhancement on Vatz
- [ ] Others(etc. e.g, documentation,...)
---

### **Please describe, what it's about or related Problem with**
> A clear description of what feature need to be developed or enhanced in Vatz 

Network monitoring plugin for inbound/outbound traffic.

### **Describe the output that you are expecting for above**
> A clear and concise description of what you expect to happen.

amount of inbound/outbound traffic with given period.

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

[node_exporter](https://github.com/prometheus/node_exporter) `node_network` metrics 

### **Additional context**
> Add any other context or screenshots about the feature request here.

**Comment by heejin-github** [comment]
heejin lee
please write a code to get network received and transmitted bytes in golang

To get the network received and transmitted bytes in Go, you can use the net and syscall packages. Here's an example code:
```go
package main

import (
    "fmt"
    "net"
    "syscall"
)

func main() {
    // Get network interfaces
    interfaces, err := net.Interfaces()
    if err != nil {
        fmt.Println(err)
        return
    }

    // Iterate through each interface and print its statistics
    for _, iface := range interfaces {
        fmt.Printf("Interface: %s\n", iface.Name)

        // Get interface statistics
        stats := &syscall.InterfaceStat{}
        err := syscall.NetIOCountersByName(iface.Name, stats)
        if err != nil {
            fmt.Println(err)
            continue
        }

        // Print statistics
        fmt.Printf("  Bytes received: %d\n", stats.BytesRecv)
        fmt.Printf("  Bytes sent: %d\n", stats.BytesSent)
    }
}

```
This code retrieves a list of network interfaces and iterates through each interface to print its statistics. For each interface, it uses the syscall.NetIOCountersByName() function to retrieve the interface statistics, which include the number of bytes received and sent.

heejin lee
how about read /proc/net/dev for this code?

Sure, you can read the /proc/net/dev file to get the network received and transmitted bytes instead of using the syscall package. Here's an example code:

```go
package main

import (
    "bufio"
    "fmt"
    "os"
    "strings"
)

func main() {
    // Open /proc/net/dev file
    file, err := os.Open("/proc/net/dev")
    if err != nil {
        fmt.Println(err)
        return
    }
    defer file.Close()

    // Create a scanner to read the file line by line
    scanner := bufio.NewScanner(file)
    for scanner.Scan() {
        line := scanner.Text()
        fields := strings.Fields(line)

        // Check if the line contains network interface statistics
        if len(fields) > 1 && strings.Contains(fields[0], ":") {
            iface := strings.Trim(fields[0], ":")
            bytesRecv := fields[1]
            bytesSent := fields[9]

            // Print statistics
            fmt.Printf("Interface: %s\n", iface)
            fmt.Printf("  Bytes received: %s\n", bytesRecv)
            fmt.Printf("  Bytes sent: %s\n", bytesSent)
        }
    }
}

```
This code reads the /proc/net/dev file and uses a scanner to read it line by line. For each line, it checks if it contains network interface statistics and extracts the interface name, number of bytes received, and number of bytes sent. Then it prints the statistics for each interface.



heejin lee
which one is prefer for the linux systems, use `syscall` package? or read `/proc/net/dev` file?

Both approaches are valid and can work on Linux systems. However, which approach to use may depend on the specific use case and the available resources.

Using the syscall package to retrieve network interface statistics is more efficient because it directly accesses the kernel's data structures and does not involve reading a file from the file system. This approach may be more suitable for applications that require real-time monitoring of network activity or that need to retrieve statistics frequently.

On the other hand, reading the /proc/net/dev file is a simpler and more portable approach that can work on any Linux system without requiring special privileges or system calls. It may be more suitable for applications that need to retrieve network statistics periodically or that do not require high performance.

In general, if performance is a critical factor and you have the necessary privileges to use the syscall package, that approach may be preferable. However, if simplicity and portability are more important, reading the /proc/net/dev file may be a better choice.

**Comment by xellos00** [comment]
@heejin-github 
Any progress for this issue?

**Comment by heejin-github** [comment]
> @heejin-github Any progress for this issue?

I'm trying to submit PR for this by next vatz bi-weekly meeting.

**Comment by heejin-github** [comment]
### PR submitted
- https://github.com/dsrvlabs/vatz-plugin-sysutil/pull/9

**Comment by xellos00** [comment]
@dsrvlabs/validator 
Please, give more feedback for this plugin if there's one. 
even for code review!!
