### ISSUE TITLE
`VATZ` Main release v1.0

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#451]
## Checklist

- [x] New Feature for the Service/Plugin (Vatz)
- [x] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. such as Ex. I'm always frustrated

This is an issue that manage our first official main release v1.0

### **Describe the solution you'd like| Ex**
> A clear and concise description of what you want to happen

We need to finish all of following items prior to main release v1.0 
- Documentation 
    - Due date (6/5/2023 KST)
    - Install guide (latest) @qkrybin, ping @xellos00 if there's anything, let's do it together.  
       - https://github.com/dsrvlabs/vatz/issues/453 
    - Public press @qkrybin
       - https://github.com/dsrvlabs/vatz/issues/454
          - twitter
          - medium
        
- Test @xellos00 (6/1/2023 KST) 
   - All CI + unit test up
   - Bug fix  

- 1.0 tagging for following repos (6/2/2023 KST) 
   - https://github.com/dsrvlabs/vatz
   - versionning  @heejin-github (금요일)
      - https://github.com/dsrvlabs/vatz-plugin-sysutil
      - https://github.com/dsrvlabs/vatz-plugin-cosmoshub

- Overall meeting, 2023-6-5 22:00 (KST)
- @qkrybin 
- @xellos00 
- @heejin-github 
- @rootwarp 

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

**Comment by xellos00** [comment]
@dsrvlabs/validator 
There's possibility to delay our first 1.0 main release due to bugs and other additional features.

## bugs
- #468
- #465 

## documentation 
- #453

**Comment by xellos00** [comment]
@heejin-github 
Can you create a RC branches as VATZ
- https://github.com/dsrvlabs/vatz/tree/v1.0.0-rc.1

**Comment by heejin-github** [comment]
> @heejin-github Can you create a RC branches as VATZ
> 
> * https://github.com/dsrvlabs/vatz/tree/v1.0.0-rc.1

Done.
- https://github.com/dsrvlabs/vatz-plugin-sysutil/tree/v1.0.0-rc.1
- https://github.com/dsrvlabs/vatz-plugin-cosmoshub/tree/v1.0.0-rc.1

**Comment by xellos00** [comment]
> > @heejin-github Can you create a RC branches as VATZ
> > 
> > * https://github.com/dsrvlabs/vatz/tree/v1.0.0-rc.1
> 
> Done.
> 
> * https://github.com/dsrvlabs/vatz-plugin-sysutil/tree/v1.0.0-rc.1
> * https://github.com/dsrvlabs/vatz-plugin-cosmoshub/tree/v1.0.0-rc.1

Thanks, let's release v1.0.0 by early next week.

**Comment by xellos00** [comment]
- https://github.com/dsrvlabs/vatz/releases

<img width="1268" alt="image" src="https://github.com/dsrvlabs/vatz/assets/6308023/54985027-321c-4714-9b2c-b504ebdaed3b">

@heejin-github 
Can you make a release draft for official plugins of v1.0.0?
so we can release tomorrow during VATZ-bi-weekly meeting.

**Comment by heejin-github** [comment]
Prepare draft for the v1.0.0
- https://github.com/dsrvlabs/vatz-plugin-cosmoshub/releases
- https://github.com/dsrvlabs/vatz-plugin-sysutil/releases

**Comment by xellos00** [comment]
# Check version on go pkg

## `2023-06-21 19:16:00 -05:00:00`
<img width="1675" alt="image" src="https://github.com/dsrvlabs/vatz/assets/6308023/df1fc4d6-0bc6-4023-afdf-ec72dc2053cc">
