### ISSUE TITLE
Panic on dispatcher

### ISSUE THREAD

**Issue by heejin-github** [dsrvlabs/vatz#465]
### Checklist
- [X] Bug from Service (Vatz)
- [ ] Bug from Plugin (Vatz) 
- [ ] Malfunction on CI/CD 
- [ ] etc(e.g, Hardware version doesn't match, )

---

### **Describe the bug**
> A clear and concise description of what the bug is.

panic happened in dispatcher.
```
panic: interface conversion: interface {} is nil, not []cron.EntryID

goroutine 41 [running]:
github.com/dsrvlabs/vatz/manager/dispatcher.(*telegram).SetDispatcher(0xc000138600, 0x30?, {0xc0?, 0x9c821a?}, {{0xc00013e8d0, 0x10}, {0xc00013e930, 0xb}, {0xc00013e8f0, 0x9}, ...})
	/root/git/vatz/manager/dispatcher/telegram.go:60 +0x37a
github.com/dsrvlabs/vatz/manager/executor.(*executor).Execute(0xedc0b7210?, {0xe1da48, 0xc00003a120}, {0xe1a338, 0xc0002bd230}, {{0xc00013e8d0, 0x10}, {0xc00013e8f0, 0x9}, 0xf, ...}, ...)
	/root/git/vatz/manager/executor/general_executor.go:57 +0x59f
github.com/dsrvlabs/vatz/cmd.multiPluginExecutor({{0xc00013e8d0, 0x10}, {0xc00013e8f0, 0x9}, 0xf, 0x1e, 0x232c, {0xc00011f4f0, 0x1, 0x1}}, ...)
	/root/git/vatz/cmd/start.go:169 +0x39e
created by github.com/dsrvlabs/vatz/cmd.startExecutor
	/root/git/vatz/cmd/start.go:135 +0x87

```

### **How to Reproduce**
> Steps to reproduce the behavior:

Run the plugin without any reminder schedule.

### **Expected behavior**
> A clear and concise description of what you expected to happen.

Run vatz and plugin well.

### **Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by heejin-github** [comment]
In issue case, entry could not be initialized for the cron when the `reminderState` is `tp.OFF`. and it cause panic as below. because the cron entry would be stored only when the reminderState becomes to `tp.ON` even once.

```
panic: interface conversion: interface {} is nil, not []cron.EntryID
```

https://github.com/dsrvlabs/vatz/blob/main/manager/dispatcher/discord.go#L45-L74
https://github.com/dsrvlabs/vatz/blob/42742c66a29b16c4f5ec12221bcf82f5c0f38fe0/manager/dispatcher/discord.go#L45-L74

https://github.com/dsrvlabs/vatz/blob/main/manager/dispatcher/telegram.go#L37-L64

https://github.com/dsrvlabs/vatz/blob/42742c66a29b16c4f5ec12221bcf82f5c0f38fe0/manager/dispatcher/telegram.go#L37-L64

**Comment by xellos00** [comment]
@heejin-github 
I found other bugs that occurs on the locals. 
Did you test net_monitoring on your local 
- #468
