### ISSUE TITLE
Add license file to official plugins

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#478]
## Checklist
- [ ] New Feature for the SVC/Plugin
- [ ] New Feature for CI/CD
- [ ] Enhancement on Vatz
- [x] Others(etc. e.g, documentation,...)
---

### **Please describe, what it's about or related Problem with**
> A clear description of what feature need to be developed or enhanced in Vatz 

There's no license file in official plugins. 
I think it's good to have in plugins as well as `VATZ`

### **Describe the output that you are expecting for above**
> A clear and concise description of what you expect to happen.

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.

### **Additional context**
> Add any other context or screenshots about the feature request here.

**Comment by xellos00** [comment]
- https://pkg.go.dev/github.com/dsrvlabs/vatz-plugin-sysutil
- https://pkg.go.dev/github.com/dsrvlabs/vatz-plugin-cosmoshub

**Comment by heejin-github** [comment]
## Add License file
- https://github.com/dsrvlabs/vatz-plugin-cosmoshub/pull/33
- https://github.com/dsrvlabs/vatz-plugin-sysutil/pull/12
