### ISSUE TITLE
Unexpected memory usage on is_alive

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#480]
- Parents: #524 

--- 
### Checklist
- [ ] Bug from Service (Vatz)
- [x] Bug from Plugin (Vatz) 
- [ ] Malfunction on CI/CD 
- [ ] etc(e.g, Hardware version doesn't match, )

---

<img width="858" alt="image" src="https://github.com/dsrvlabs/vatz/assets/6308023/f280c034-91d1-4d22-964a-15e08f958f3d">

<img width="1196" alt="image" src="https://github.com/dsrvlabs/vatz/assets/6308023/b3f49630-1e13-499f-bbda-e3cc69e6ff19">

### **Describe the bug**
> A clear and concise description of what the bug is.

### **How to Reproduce**
> Steps to reproduce the behavior:

2. '...'

### **Expected behavior**
> A clear and concise description of what you expected to happen.

### **Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by gnongs** [comment]
## Test
I will run vatz and plugins for testing on `agoric-testnet-validator-do-fra1`.

Before we start, I will update Vatz and the plugins to a recent version.
```sh

```

**Comment by gnongs** [comment]
## Edit code
I will add pprof package on `is_alived` plugin.

**Comment by gnongs** [comment]
## Change node_is_alive plugin to one with `pprof`.
```sh
ot@agoric-testnet-validator-do-fra1:~/dsrv/bin/vatz# ./vatz_stop.sh

pid=`pidof vatz`
process=vatz

kill -15 $pid
sleep 1

while (( `lsof -p $pid | wc -l` > 0 ))
do
    echo `lsof -p $pid | wc -l`
    sleep 1
done

echo "${process}(${pid}) is killed."
vatz(2073843) is killed.
```
```sh
root@agoric-testnet-validator-do-fra1:~/.vatz# mv node_is_alived ../tmp/
```
```sh
root@agoric-testnet-validator-do-fra1:~/git# git clone https://github.com/dsrvlabs/vatz-plugin-cosmoshub.git
Cloning into 'vatz-plugin-cosmoshub'...
remote: Enumerating objects: 501, done.
remote: Counting objects: 100% (124/124), done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 501 (delta 54), reused 79 (delta 32), pack-reused 377
Receiving objects: 100% (501/501), 7.21 MiB | 4.06 MiB/s, done.
Resolving deltas: 100% (230/230), done.
root@agoric-testnet-validator-do-fra1:~/git# cd vatz-plugin-cosmoshub/plugins/node_is_alived/
root@agoric-testnet-validator-do-fra1:~/git/vatz-plugin-cosmoshub/plugins/node_is_alived# git checkout gnong
Branch 'gnong' set up to track remote branch 'gnong' from 'origin'.
Switched to a new branch 'gnong'
root@agoric-testnet-validator-do-fra1:~/git/vatz-plugin-cosmoshub/plugins/node_is_alived# go install main.go
warning: GOPATH set to GOROOT (/usr/local/go) has no effect
root@agoric-testnet-validator-do-fra1:~/git/vatz-plugin-cosmoshub/plugins/node_is_alived# mv /usr/local/bin/main /root/.vatz/node_is_alived
```

**Comment by xellos00** [comment]
@gnongs 
Please, keep on watch about 2 weeks, it's okay for the moment, but later on, It's getting bigger in memory usage.

**Comment by rootwarp** [comment]
@gnongs @xellos00 
Recommend to close client and response body instances after using those.
`defer` will be useful.

**Comment by gnongs** [comment]
> @gnongs Please, keep on watch about 2 weeks, it's okay for the moment, but later on, It's getting bigger in memory usage.

@xellos00 
I think we don't need to keep on watch for about 2 weeks. Because `is_alived` plugin already used memory usage more than others.

```sh
root@agoric-testnet-validator-do-fra1:~/dsrv/bin/etc# cat mem_usage.sh
#!/bin/bash

ps aux | ps aux | awk '{print $6/1024 " MB\t\t" $11}' | sort -n -r | grep vatz
root@agoric-testnet-validator-do-fra1:~/dsrv/bin/etc# bash mem_usage.sh
60.3477 MB		/root/.vatz/node_is_alived
22.3047 MB		vatz
14.6875 MB		/root/.vatz/node_governance_alarm
13.5742 MB		/root/.vatz/node_peer_count
12.2227 MB		/root/.vatz/node_block_sync
11.8906 MB		/root/.vatz/node_active_status
10.8633 MB		/root/.vatz/mem_monitor
10.8125 MB		/root/.vatz/cpu_monitor
10.3438 MB		/root/.vatz/disk_monitor
```

So we're going to check the pprof data based on the current.

**Comment by gnongs** [comment]
> @gnongs @xellos00 Recommend to close client and response body instances after using those. `defer` will be useful.
> 
> * ref. https://medium.com/@chaewonkong/solving-memory-leak-issues-in-go-http-clients-ba0b04574a83

@rootwarp 
Thank you for your advice. I will setup with `defer resp.Body.Close()` on `kyve-testnet-validator-do-fra1`.

And I compare agoric with kyve.

> Commit: https://github.com/dsrvlabs/vatz-plugin-cosmoshub/commit/3eb3ad32646e4a0aa44731c65175bcfec81df79c

**Comment by gnongs** [comment]
## 2023-10-28
I checked both machine.

- agoric-testnet-validator-do-fra1(Not set to close HTTP client)
```sh
root@agoric-testnet-validator-do-fra1:~/dsrv/bin/etc# bash mem_usage.sh
62.4609 MB		/root/.vatz/node_is_alived
....
```

- kyve-testnet-validator-do-fra1(Set to close HTTP client)
```sh
root@kyve-testnet-validator-do-fra1:~/dsrv/bin/vatz# bash mem_usage.sh
....
4.59766 MB		/root/.vatz/node_is_alived
....
```

**Comment by gnongs** [comment]
@xellos00 @rootwarp 

My guess is that it's a memory leak caused by not closing the http client, as @rootwarp mentioned.

So I'll make sure all my plugins add that part.

**Comment by gnongs** [comment]
## 2023-10-30
- Agoric
```sh
root@agoric-testnet-validator-do-fra1:~/dsrv/bin/etc# bash mem_usage.sh
178.469 MB		/root/.vatz/node_is_alived
22.293 MB		vatz
14.7188 MB		/root/.vatz/node_governance_alarm
14.4961 MB		/root/.vatz/node_peer_count
12.5664 MB		/root/.vatz/node_block_sync
12.207 MB		/root/.vatz/node_active_status
11.3086 MB		/root/.vatz/mem_monitor
11.2344 MB		/root/.vatz/cpu_monitor
11.1562 MB		/root/.vatz/disk_monitor
```

- Kyve
```sh
root@kyve-testnet-validator-do-fra1:~/dsrv/bin/vatz# bash mem_usage.sh
6.41406 MB		/root/.vatz/node_governance_alarm
4.99609 MB		vatz
4.23438 MB		/root/.vatz/node_is_alived
2.70312 MB		/root/.vatz/disk_monitor
```

**Comment by gnongs** [comment]
Created PR: https://github.com/dsrvlabs/vatz-plugin-cosmoshub/pull/35

**Comment by xellos00** [comment]
@gnongs 

Thanks for confirming!
