### ISSUE TITLE
plugin command can't load specified config

### ISSUE THREAD

**Issue by rootwarp** [dsrvlabs/vatz#481]
### Checklist
- [x] Bug from Service (Vatz)
- [ ] Bug from Plugin (Vatz) 
- [ ] Malfunction on CI/CD 
- [ ] etc(e.g, Hardware version doesn't match, )

---

### **Describe the bug**
> A clear and concise description of what the bug is.

If we want to specify config file(not using default.yaml), we can add `--config` flag to start `vatz`.
But when we try to install plugins by using `plugin` command, `--config` flag is not available to specify Vatz config right now.

### **How to Reproduce**
> Steps to reproduce the behavior:

`start` command supports `--config` flag.
```
rootwarp@mindhack ~/g/d/vatz test? > ./vatz start --help
start VATZ

Usage:
   start [flags]

Flags:
      --config string       VATZ config file. (default "default.yaml")
  -h, --help                help for start
      --log string          log file export to.
      --prometheus string   prometheus port number. (default "18080")
```

But `plugin` command does not.
```
rootwarp@mindhack ~/g/d/vatz test? > ./vatz plugin install --help
Install new plugin

Usage:
   plugin install [flags]

Examples:
vatz plugin install <plugin's githubAddress> <pluginName>

Flags:
  -h, --help             help for install
  -v, --version string   Installed plugin version
```

### **Expected behavior**
> A clear and concise description of what you expected to happen.

`--config` flag should be available for all `plugin` command.
Additionally, the specified config file should be loaded appropriately.

### **Screenshots**
> If applicable, add screenshots to help explain your problem.

N/A

**Comment by rootwarp** [comment]
Issued by @skonhwang

**Comment by xellos00** [comment]
@rootwarp 
is this to handle multiple files in config?

**Comment by rootwarp** [comment]
> @rootwarp 
> 
> is this to handle multiple files in config? 

No. to run multiple vatz agent in one machine.

**Comment by xellos00** [comment]
> > @rootwarp
> > is this to handle multiple files in config?
> 
> No. to run multiple vatz agent in one machine with different config.

Maybe, My question is not clear enough. 
this is mainly targets different environments, for VATZ agent such as 

- run VATZ1 with config_1: default.yaml with -home_path ~vatz
- run VATZ1 with config_2: default2.yaml with -home_path ~vatz2
- run VATZ1  with config_3: default3.yaml with -home_path ~vatz3

or 

set one or more vatz agent in single machine 
- run VATZ1 with config_1: default.yaml with -home_path ~vatz
- run VATZ2 with config_2: default2.yaml with -home_path ~vatz2
- run VATZ3  with config_3: default3.yaml with -home_path ~vatz3

**Comment by rootwarp** [comment]
@xellos00 Thanks for more detail info.
Exactly, second scenario.

**Comment by skonhwang** [comment]
> @xellos00 Thanks for more detail info. Exactly, second scenario.
> 
> For more details, in some protocol, we are operating different clients in one machine. That's why @skonhwang tested for this scenario.

As we know, demeter is infra structure and there are many protocol (obol, ssv, etherfi). Each protocol has own alert channel and these want to send  alert message to own channel. In case of etherfi, it has etherfi-sync-clientv2 and other protocol does not have it so the alert message caused by etherfi-sync-clientv2 doesn't need other protocol.
So it is the reason why I want to run vatz_another for etherfi only.
