### ISSUE TITLE
Advertising (Commercial) VATZ to other protocols (through Discord, Telegram, etc)

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#489]
## Checklist
- [ ] New Feature for the SVC/Plugin
- [ ] New Feature for CI/CD
- [ ] Enhancement on Vatz
- [x] Others(etc. e.g, documentation,...)
---

As we release v1.0, I think it's time to express our development to COSMOS at least. 
We haven't tried yet this before, but it's good time that to express on Validator to use this on public.

**Comment by xellos00** [comment]
# Vote

**Comment by xellos00** [comment]
@dsrvlabs/validator 

Is this okay to advertise on Every protocol's on discord or other method (telegram, etc)

- Go 👍🏽 
- Give up ❤️

**Comment by xellos00** [comment]
@qkrybin 
Can you help us to create an advertising phrases on discord as Validator?
I will tell you the details what we had discussed in VATZ-bi-weekly meeting.

**Comment by qkrybin** [comment]
> @qkrybin Can you help us to create an advertising phrases on discord as Validator? I will tell you the details what we had discussed in VATZ-bi-weekly meeting.


DSRV presents **🔥 VATZ 🔥**
A next-level, open-source tool for building, analyzing, and managing node infrastructure 🧰
You can check node states in real time and receive alerts for all blockchain protocols, including metrics that the protocol itself might not support! 

📢 Why did we make this? 
✅ Running a node is hard work folks. We’re talking malfunctions, bugs, penalties– it can get messy. 
✅ You deserve a simple and cost-effective option!
✅ We believe in the power of open-source– the ball is now in your court 🎾

💡 So how does it work?
VATZ is made up of 3 parts: 
⚙️ VATZ-Proto
⚙️ VATZ (SVC)
⚙️ VATZ Plugins (SDK) 
👉 Together these provide features such as Multi-Protocol Support, Infra as Code, Monitoring, and more!
VATZ provides plugins for system utility and Cosmos Hub for now, you could easily create your own plugin using the provided SDK.

📍How to get started?
Visit VATZ repo and follow step by step guide! 
- gitbub: https://github.com/dsrvlabs/vatz

VATZ is a community effort 🙏 
Come try it out, suggest improvements, and help shape the space. 


--- 
@xellos00 does it look ok?

**Comment by xellos00** [comment]
> > @qkrybin Can you help us to create an advertising phrases on discord as Validator? I will tell you the details what we had discussed in VATZ-bi-weekly meeting.
> 
> DSRV presents **🔥 VATZ 🔥** A next-level, open-source tool for building, analyzing, and managing node infrastructure 🧰 You can check node states in real time and receive alerts for all blockchain protocols, including metrics that the protocol itself might not support!
> 
> 📢 Why did we make this? ✅ Running a node is hard work folks. We’re talking malfunctions, bugs, penalties– it can get messy. ✅ You deserve a simple and cost-effective option! ✅ We believe in the power of open-source– the ball is now in your court 🎾
> 
> 💡 So how does it work? VATZ is made up of 3 parts: ⚙️ VATZ-Proto ⚙️ VATZ (SVC) ⚙️ VATZ Plugins (SDK) 👉 Together these provide features such as Multi-Protocol Support, Infra as Code, Monitoring, and more! VATZ provides plugins for system utility and Cosmos Hub for now, you could easily create your own plugin using the provided SDK.
> 
> 📍How to get started? Visit VATZ repo and follow step by step guide!
> 
> * gitbub: https://github.com/dsrvlabs/vatz
> 
> VATZ is a community effort 🙏 Come try it out, suggest improvements, and help shape the space.
> 
> @xellos00 does it look ok?

I think it's good to post as it is,  but let's do this after our company ceremony that is addressed in the first week of September.

**Comment by xellos00** [comment]
- Things to discuss
- Is there any comment for this? 
- Assignees

**Comment by xellos00** [comment]
# `Assignees `
## DK
- Shentu
- Burnt

**Comment by xellos00** [comment]
# Sample for everyone

**Comment by xellos00** [comment]
```
DSRV presents **🔥 VATZ 🔥** 
A next-level, open-source tool for building, analyzing, and managing node infrastructure 🧰
You can check node states in real time and receive alerts for all blockchain protocols, including metrics that the protocol itself might not support! 

📢 Why did we make this? 
✅ Running a node is hard work folks. We’re talking malfunctions, bugs, penalties– it can get messy. 
✅ You deserve a simple and cost-effective option!
✅ We believe in the power of open-source– the ball is now in your court 🎾

- ⚙️ VATZ: https://github.com/dsrvlabs/vatz 
- official VATZ Plugin
   - https://github.com/dsrvlabs/vatz-plugin-cosmoshub
   - https://github.com/dsrvlabs/vatz-plugin-sysutil 
   
👉 Together these provide features such as Multi-Protocol Support, Infra as Code, Monitoring, and more!
VATZ provides plugins for system utility and Cosmos Hub for now, you could easily create your own plugin using the provided SDK.


VATZ is a community effort 🙏 
Come try it out, suggest improvements, and help shape the space. 
```

**Comment by xellos00** [comment]
Hey, Guys
Here's a new tool that can manage sei plugins and more!!

DSRV presents **🔥 VATZ 🔥** 
A next-level, open-source tool for building, analyzing, and managing node infrastructure 🧰
You can check node states in real time and receive alerts for all blockchain protocols, including metrics that the protocol itself might not support! 

## You can manage your `sei network` validator node with more efficiency.

- ⚙️  [VATZ](https://github.com/dsrvlabs/vatz)
    > VATZ service that runs to collect metric info and send notification and more+  
    
- ⚙️  [vatz-plugin-sei](https://github.com/dsrvlabs/vatz-plugin-sei)
   > Monitoring Sei Validator node's 
     - `node_block_sync` : monitor block sync status
     - `node_is_alived` : monitor process running status
     - `node_peer_count` : monitor the number of peers
     - `node_active_status` : monitor the validator include in active set
     - `node_governance_alarm` : monitor the new governance proposal and whether or not to vote
     - `pfd_status`: monitor the price-feeder oracle status

### We also provide other metrics with `VATZ` official plugins
- Official VATZ Plugins
   - > Monitoring node's hardware status in metric of
   ⚙️ [vatz-plugin-sysutil](https://github.com/dsrvlabs/vatz-plugin-sysutil) 
      
        - `CPU`  
        - `Memory` 
        - `Disk`, 
        - `Network Traffic`
   - ⚙️ [vatz-plugin-cosmoshub](https://github.com/dsrvlabs/vatz-plugin-cosmoshub)
      > Monitoring node's status of any cosmos protocols in metric of
        - `node_block_sync`
        - `node_is_alived`
        - `node_peer_count`
        - `node_active_status`
        - `node_governance_alarm`
 
👉 Together these provide features such as Multi-Protocol Support, Infra as Code, Monitoring, and more!
VATZ provides plugins for system utility and Cosmos Hub for now, you could easily create your own plugin using the provided SDK.

VATZ is a community effort 🙏 
Come try it out, suggest improvements, and help shape the space. 

📍How to get started?
Visit VATZ repo and follow the step by step guide!
- gitbub: https://github.com/dsrvlabs/vatz

## to make it easier to get started for `sei-network`
Please, follow the instruction in here !!
- https://gist.github.com/meetrick/c2bff627dbe430503a296980ba3dc46a

**Comment by xellos00** [comment]
Hey, Guys
Here's a new tool that can manage sei plugins and more!! 

DSRV presents **🔥 VATZ 🔥** 
A next-level, open-source tool for building, analyzing, and managing node infrastructure 🧰
You can check node states in real time and receive alerts for all blockchain protocols, including metrics that the protocol itself might not support! 

## You can manage your `sei network` validator node with more efficiency.

- ⚙️  [VATZ](https://github.com/dsrvlabs/vatz)
    > VATZ service that runs to collect metric info and send notification and more+  
    
- ⚙️  [vatz-plugin-sei](https://github.com/dsrvlabs/vatz-plugin-sei)
   > Monitoring Sei Validator node's 
     - `node_block_sync` : monitor block sync status
     - `node_is_alived` : monitor process running status
     - `node_peer_count` : monitor the number of peers
     - `node_active_status` : monitor the validator include in active set
     - `node_governance_alarm` : monitor the new governance proposal and whether or not to vote
     - `pfd_status`: monitor the price-feeder oracle status

### We also provide other metrics with `VATZ` official plugins
- Official VATZ Plugins
   - > Monitoring node's hardware status in metric of
   ⚙️ [vatz-plugin-sysutil](https://github.com/dsrvlabs/vatz-plugin-sysutil) 
      
        - `CPU`  
        - `Memory` 
        - `Disk`, 
        - `Network Traffic`
   - ⚙️ [vatz-plugin-cosmoshub](https://github.com/dsrvlabs/vatz-plugin-cosmoshub)
      > Monitoring node's status of any cosmos protocols in metric of
        - `node_block_sync`
        - `node_is_alived`
        - `node_peer_count`
        - `node_active_status`
        - `node_governance_alarm`
 
👉 Together these provide features such as Multi-Protocol Support, Infra as Code, Monitoring, and more!
VATZ provides plugins for system utility and Cosmos Hub for now, you could easily create your own plugin using the provided SDK.

VATZ is a community effort 🙏 
Come try it out, suggest improvements, and help shape the space. 

📍How to get started?
Visit VATZ repo and follow the step by step guide!
- gitbub: https://github.com/dsrvlabs/vatz

## to make it easier to get started for `sei-network`
Please, follow the instruction in here !! 
- https://gist.github.com/meetrick/c2bff627dbe430503a296980ba3dc46a

**Comment by xellos00** [comment]
## We also provide our official plugins for any cosmos protocols as well as its hardware status to monitor and manage overall.  

### Other metrics with `VATZ` official plugins

- Official VATZ Plugins
   - ⚙️ [vatz-plugin-sysutil](https://github.com/dsrvlabs/vatz-plugin-sysutil) 
      > Monitoring node's hardware status in metric of
        - `CPU`  
        - `Memory` 
        - `Disk`, 
        - `Network Traffic`
   - ⚙️ [vatz-plugin-cosmoshub](https://github.com/dsrvlabs/vatz-plugin-cosmoshub)
      > Monitoring node's status of any cosmos protocols in metric of
        - `node_block_sync`
        - `node_is_alived`
        - `node_peer_count`
        - `node_active_status`
        - `node_governance_alarm`
 
👉 Together these provide features such as Multi-Protocol Support, Infra as Code, Monitoring, and more!
VATZ provides plugins for system utility and Cosmos Hub for now, you could easily create your own plugin using the provided SDK.

VATZ is a community effort 🙏 
Come try it out, suggest improvements, and help shape the space.

**Comment by xellos00** [comment]
I am closing this issue, since all commercial post has been uploaded as [above](https://github.com/dsrvlabs/vatz/issues/489#issuecomment-1717609442)
