### ISSUE TITLE
Cosmos - Plugin - Developed a VATZ cosmos plugin for Sei-network

### ISSUE THREAD

**Issue by meetrick** [dsrvlabs/vatz#498]
## Checklist

- [x] New Feature for the Service/Plugin (Vatz)
- [ ] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> There is no problem with the cosmos plugin. The `sei-network` node, which recently launched its mainnet, uses a different API, so it can't use all the existing VATZ cosmos plugins.

### **Describe the solution you'd like| Ex**
> Modify the APIs of `node_block_sync` and `node_peer_count` to enable VATZ monitoring on sei-network.
> Create a price feeder monitoring plugin.

### **Describe alternatives you've considered**
> Modify the APIs of `node_block_sync` and `node_peer_count` to enable VATZ monitoring on sei-network.
> Create a price feeder monitoring plugin.

### **Additional context or comment**
> Currently, the sei-network does not have a monitoring tool published by the community other than the monitoring grafana published by the foundation. We will try to share this with the foundation and community to get additional delegation.

**Comment by xellos00** [comment]
@meetrick 
All looks good to me regarding an issue you raised.

btw are you planning to put an identifier to distinctly call which API should call between Sei and other cosmos protocols regarding `node_block_sync` and  `node_peer_count ` functions?
or other ideas you might have?

**Comment by meetrick** [comment]
> @meetrick All looks good to me regarding an issue you raised.
> 
> btw are you planning to put an identifier to distinctly call which API should call between Sei and other cosmos protocols regarding `node_block_sync` and `node_peer_count ` functions? or other ideas you might have?

 I tried creating a branch for sei-network in the existing `vatz-plugin-cosmoshub`, but I had trouble installing the vatz plugin, so I created a new vatz-pluin-sei repo.
 
- https://github.com/dsrvlabs/vatz-plugin-sei

**Comment by meetrick** [comment]
- @xellos00 Implemented the pfd-status plugin. Reviews and comments are appreciated.
  - https://github.com/dsrvlabs/vatz-plugin-sei/blob/main/plugins/pfd_status/main.go

**Comment by meetrick** [comment]
## Status
Done
