### ISSUE TITLE
SDK.Response include AlerType in Response yet, it doesn't requires anymore since we put this config in default.yaml

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#499]
## Checklist

- [ ] New Feature for the Service/Plugin (Vatz)
- [x] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. such as Ex. I'm always frustrated

in developments of VATZ very Early, Plugins' response requires AlertType but we don't have to set in Plugin anymore since we do have dispatcher config in Vatz config. 

### **Describe the solution you'd like| Ex**
> A clear and concise description of what you want to happen

Get rid of AlertType from `SDK.Response` from proto buffer.  

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

Repo List
- VATZ proto: https://github.com/dsrvlabs/vatz-proto/pull/19
- VATZ: https://github.com/dsrvlabs/vatz/pull/505
- Plugins 
   - vatz-plugin-sysutil : https://github.com/dsrvlabs/vatz-plugin-sysutil/pull/14
   - vatz-plugin-cosmoshub : https://github.com/dsrvlabs/vatz-plugin-cosmoshub/pull/34
   
### **Additional context or comment**
> Add any other context or screenshots about the feature request here.

<img width="858" alt="image" src="https://github.com/dsrvlabs/vatz/assets/6308023/fe56728e-16fe-4343-8276-c1af4713c9af">

**Comment by xellos00** [comment]
@heejin-github 
I think it requires update on both side, 
I will handle `VATZ` side, 
will you handle both of our official plugins 
- https://github.com/dsrvlabs/vatz-plugin-cosmoshub
- https://github.com/dsrvlabs/vatz-plugin-sysutil

Let me know what you think of, because I think we need to update at once.

**Comment by heejin-github** [comment]
> @heejin-github I think it requires update on both side, I will handle `VATZ` side, will you handle both of our official plugins
> 
> * https://github.com/dsrvlabs/vatz-plugin-cosmoshub
> * https://github.com/dsrvlabs/vatz-plugin-sysutil
> 
> Let me know what you think of, because I think we need to update at once.

As we talked on the meeting, I'll remove `AlertTypes` from official plugin, and I'll prepare PR for it soon. let me know if you ready on `Vatz` side. 
Thank you!

**Comment by heejin-github** [comment]
@xellos00 
Uploaded PR as below.
- https://github.com/dsrvlabs/vatz-plugin-cosmoshub/pull/34
- https://github.com/dsrvlabs/vatz-plugin-sysutil/pull/14

**Comment by xellos00** [comment]
> > @heejin-github I think it requires update on both side, I will handle `VATZ` side, will you handle both of our official plugins
> > 
> > * https://github.com/dsrvlabs/vatz-plugin-cosmoshub
> > * https://github.com/dsrvlabs/vatz-plugin-sysutil
> > 
> > Let me know what you think of, because I think we need to update at once.
> 
> As we talked on the meeting, I'll remove `AlertTypes` from official plugin, and I'll prepare PR for it soon. let me know if you ready on `Vatz` side. Thank you!

Appreciate it. let's do this all together.
