### ISSUE TITLE
Issue on Github action auto compile on proto in `VATZ-proto`

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#506]
- Related: #385 
---
### Checklist
- [x] Bug from Service (Vatz)
- [ ] Bug from Plugin (Vatz) 
- [ ] Malfunction on CI/CD 
- [ ] etc(e.g, Hardware version doesn't match, )

---

### **Describe the bug**
> A clear and concise description of what the bug is.

when you update protobuffer in vatz-proto, there's error causes,
as https://github.com/dsrvlabs/vatz-proto/actions/runs/6476709871

### **How to Reproduce**
> Steps to reproduce the behavior:

1. Update proto-proto
2. merge the code
3. auto-compile fails

### **Expected behavior**
> A clear and concise description of what you expected to happen.

- create a proper protobuffer 

### **Screenshots**
> If applicable, add screenshots to help explain your problem.

<img width="1664" alt="image" src="https://github.com/dsrvlabs/vatz/assets/6308023/b8a80420-aa3f-4157-a880-e0ffeda65513">

**Comment by kim201212** [comment]
@xellos00 Can you check to expire the `VATZ_PROTO_ACTION_TOKEN`
https://github.com/dsrvlabs/vatz-proto/blob/main/.github/workflows/ci_proto_auto_compile.yml#L17

**Comment by xellos00** [comment]
> @xellos00 Can you check to expire the `VATZ_PROTO_ACTION_TOKEN`
> 
> Location: Settings -> General -> Security -> Secrets and variables -> Actions
> 
> https://github.com/dsrvlabs/vatz-proto/blob/main/.github/workflows/ci_proto_auto_compile.yml#L17

I will take look on it.

**Comment by xellos00** [comment]
<img width="1661" alt="image" src="https://github.com/dsrvlabs/vatz/assets/6308023/55848baa-c089-4d93-ae69-61f33b34ea27">

@kim201212

**Comment by xellos00** [comment]
confirmed with @kim201212
