### ISSUE TITLE
VATZ-Proto submodule update with latest version

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#507]
## Checklist

- [ ] New Feature for the Service/Plugin (Vatz)
- [x] Enhancement (Vatz)
- [ ] others(etc. e.g, documentation, project policy management)

---
### **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. such as Ex. I'm always frustrated

current vatz-proto submodule google apis is committed about 8 month ago, and therefore we need to update sub-module to prevent unexpected error with compile. 

- https://github.com/dsrvlabs/vatz-proto

### **Describe the solution you'd like| Ex**
> A clear and concise description of what you want to happen

### **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you have considered.

### **Additional context or comment**
> Add any other context or screenshots about the feature request here.

**Comment by rootwarp** [comment]
```
rootwarp@mindhack ~/g/d/vatz-proto submodule! > git submodule update --remote
...
...
...
rootwarp@mindhack ~/g/d/vatz-proto submodule! > make all
make init
make[1]: Entering directory '/home/rootwarp/git/dsrv/vatz-proto'
go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
go: downloading google.golang.org/grpc/cmd/protoc-gen-go-grpc v1.3.0
go: downloading google.golang.org/grpc v1.58.3
make[1]: Leaving directory '/home/rootwarp/git/dsrv/vatz-proto'
make build
make[1]: Entering directory '/home/rootwarp/git/dsrv/vatz-proto'
make[1]: Leaving directory '/home/rootwarp/git/dsrv/vatz-proto'
```

**Comment by xellos00** [comment]
@rootwarp 
Guess we can close this issue since we merged all related PRs unless you do have other concerns with it. 
- https://github.com/dsrvlabs/vatz-proto/pull/21
- https://github.com/dsrvlabs/vatz/pull/508

**Comment by rootwarp** [comment]
> @rootwarp 
> 
> Guess we can close this issue since we merged all related PRs unless you do have other concerns with it. 
> 
> - https://github.com/dsrvlabs/vatz-proto/pull/21
> 
> - https://github.com/dsrvlabs/vatz/pull/508

Agree and thanks
