### ISSUE TITLE
Meeting notes on 2024-04-01 16:00:00 +09:00:00

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#553]
- Parents: #550

**Comment by xellos00** [comment]
# Meeting Notes
- Node Manager 
   - VATZ V1: Score 70 overall

**Comment by xellos00** [comment]
# Next Things to Discusss

- [ ] Are we going to use Vatz as Back up Method for the next monitoring. 
- [ ] what's the secondary method if we are not using or next developments  
- [ ] Watcher / Manager / Planning.

**Comment by xellos00** [comment]
@rootwarp 
I this okay to proceed free plan for test? 
![image](https://github.com/dsrvlabs/vatz/assets/6308023/23492205-07a5-4503-aa78-e5f812b201cd)

**Comment by rootwarp** [comment]
@xellos00 You can use `validator-test-umilited`.

**Comment by xellos00** [comment]
Transferred to issue 
- https://github.com/dsrvlabs/vatz/issues/555
