### ISSUE TITLE
Watcher - First Kick off Meeting for the development

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#564]
- Parents: https://github.com/dsrvlabs/vatz/issues/557
- Related: https://github.com/dsrvlabs/vatz/discussions/559#discussioncomment-9587248

---

**Comment by xellos00** [comment]
@kim201212 
I apologize for late update for the meeting schedule, btw
I would like to hold a meeting on this Thursday night, and make this quick. 
if it doesn't work for you let me know.

**Comment by meetrick** [comment]
> Are you available on this Thursday night `2024/5/30 (KST)`?
> 
> 

I got it!

**Comment by xellos00** [comment]
# Invitation has sent

<img width="471" alt="image" src="https://github.com/dsrvlabs/vatz/assets/6308023/88568930-2f2f-43b6-803a-a55655a7038f">

**Comment by xellos00** [comment]
# Meeting Agenda

- 일정: 2024년 7월 9일 까지
    - 개발 2024년 7월2일  
       - @kim201212 (주)
       - @xellos00 (부)
    - QA 2024년 7월2일  
       - @meetrick  (주) 
       - @xellos00 (부)
       - @kim201212 (부)
- Test Protocol
    - 오스모시스 (@meetrick) 블록생성 Time이 3초 가량으로 줄었기 때문에, 가장 효율적인 테스트 Protocol 이라고 생각함.  

- 플러그인 개발 방안
   > @kim201212 
   > Watcher 의 개념은 API를 이용해 Explorer 개념에서 API를 활용해 Validator의 확인한다 하지만 이는 dependency가 Explorer에 걸리 수 있으니, 이보다는 블록을 확인해 Sign한 증거를 확인한다. 
   @kim201212 
   플러그인 Metric 예상 수집 절차  
   1. 블록을 확인하고 그 안에 우리 Validator가 제대로 Sign이 되어 있는지를 확인 
   2. 각 플러근의 Flag 통해 각 플러그인에서 각 Missing Count에 Metric을 유저가 설정후 Alert 발생. 
    
 - 실 개발
    - 플러그인 개발 
       - @kim201212, 주담당 
       - @xellos00, 보조
       - @meetrick 주 테스트 
    - VATZ 개발
       - Docker K8s 개발  @xellos00

**Comment by xellos00** [comment]
> # TO DOs
> > Last week of May (~ 2024/5/31)
> 
> * [x]  Repo 만들기 -> performed in issue [Dev - Create a new Repository for Watcher  vatz-plugin-watcher-cosmos#4](https://github.com/dsrvlabs/vatz-plugin-watcher-cosmos/issues/4)
> * [x]  오스모시스 API 조사 -> Transferred to [Dev - Osmosis API research  vatz-plugin-watcher-cosmos#2 (comment)](https://github.com/dsrvlabs/vatz-plugin-watcher-cosmos/issues/2#issuecomment-2140080994)

All Todo has been transferred to issues as above in Repo 
- https://github.com/dsrvlabs/vatz-plugin-watcher-cosmos
