### ISSUE TITLE
Add new discord webhook address type

### ISSUE THREAD

**Issue by heejin-github** [dsrvlabs/vatz#576]
### Checklist
- [x] Bug from Service (Vatz)
- [ ] Bug from Plugin (Vatz) 
- [ ] Malfunction on CI/CD 
- [ ] etc(e.g, Hardware version doesn't match, )

---

### **Describe the bug**
> A clear and concise description of what the bug is.
discord webhook address was changed to `https://discordapp.com/`

### **How to Reproduce**
> Steps to reproduce the behavior:
running vatz with new webhook address from discord 

### **Expected behavior**
> A clear and concise description of what you expected to happen.
sending discord message 

### **Screenshots**
> If applicable, add screenshots to help explain your problem.

**Comment by xellos00** [comment]
@heejin-github 
Can you close this issue? I think it's been resolved since last PR that you raised.
