### ISSUE TITLE
vatz-proto buffer's Github action enhancement

### ISSUE THREAD

**Issue by xellos00** [dsrvlabs/vatz#87]
- Parents: #248 
---
## Checklist
- [ ] New Feature for the Service/Plugin (Vatz)
- [x] Enhancement (Vatz)
- [ ] others(etcm ie, documentation)

**Is your feature request related to a problem? Please describe.**
Github action is not fully working as expected.

- [ ] 1. How to compare proto-buff is updated when it has compiled
- [ ] 2. There's no version for now. How to check the version.  
- [ ] 3. Skip if there's nothing to commit. (add more conditions)

---

- make neat below action
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/6308023/165232291-b0ffc5a2-1377-4fb2-aa05-2d8f3ba67c46.png">

- make clean
if there's no folder and then it skip for next

**Describe the solution you'd like**
fails when there's nothing to commit. 
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/6308023/165400094-ade7517b-6277-4618-bb4b-4f45c9bd7aa5.png">

**Comment by xellos00** [comment]
@kim201212 
Can you record whole history of this issue that relate to 
- https://github.com/dsrvlabs/vatz-proto/issues/14

let me know when you finish this, so I can close both items.

**Comment by kim201212** [comment]
For this CI to work, the CI bot needs to have push permissions. 
Since we can't just give it push permissions, we can work around this by giving the CI bot the admin role.
But I think it's dangerous to give the bot the admin role. It's something to consider and decide.
